### ISSUE TITLE
希望添加mermaid支持

### ISSUE THREAD

**Issue by fevenor** [purocean/yn#10]
mermaid无需外部编辑器或Java环境即可绘制流程图

**Comment by purocean** [comment]
其实这个最初我是加了的，因为那时候我考虑是自用，觉得还是 plantuml 好，就在 [1.80.0](https://github.com/purocean/yn/releases/tag/v1.18.0) 版本移除了。现在喜欢使用 drawio 导出为包含为副本的 png，可以直接嵌入任何 markdown 解析器，而且可以再次编辑。

现在这个编辑器定位不只是自己用了，那么我还是加回来吧 :)

**Comment by purocean** [comment]
https://github.com/purocean/yn/releases/tag/v2.0.0-beta9.0
