### ISSUE TITLE
可以在readme中添加一下对release版本中blockmap的说明吗？

### ISSUE THREAD

**Issue by xtay573269555** [purocean/yn#100]
你好，我看到关于这个软件的介绍，想试用一下。但是在下载的时候，不知道该下载哪个版本了。
可以在readme中添加一下对release版本中blockmap的说明吗？我在readme中找不到blockmap关键字，google搜索 Yank Note blockmap 也找不到说明。
建议说明一下，以免新用户不知道该使用哪个版本。虽然readme也留了微信，但每来一个新人就重复解释一下这个基本的问题，也挺消耗维护人员时间精力的。

**Comment by xtay573269555** [comment]
好吧，我刚才没注意单位。这个 blockmap 应该是校验文件，第一次见到。以前都是 asc 或 sha512 之类的。

**Comment by purocean** [comment]
是的，这个文件主要是用于增量更新下载用。更多细节可以看看 https://www.electron.build/auto-update.html 这个。
