### ISSUE TITLE
Plantuml 加载非常慢

### ISSUE THREAD

**Issue by ScottYueqiang** [purocean/yn#105]
使用 Yank Note使用plantuml编写，预览图一直加载不出来

**Comment by ScottYueqiang** [comment]
duplicate

**Comment by purocean** [comment]
试试新版本，新版本增加了渲染端口配置，配置成 PlantUML 官方端点可能快一些。如果版本过低也可能是 BUG #99

**Comment by ScottYueqiang** [comment]
> 试试新版本，新版本增加了渲染端口配置，配置成 PlantUML 官方端点可能快一些。如果版本过低也可能是 BUG #99
好的，谢谢
