### ISSUE TITLE
能不能增加一个像Typora边输入边渲染的功能，只用一个屏幕，不左右分屏

### ISSUE THREAD

**Issue by nicken** [purocean/yn#109]
现在的输入模型，太浪费屏幕了，左边输入，右边看效果；
能不能像Typora边输入边渲染的功能，只用一个屏幕，不左右分屏；
有时就是简单的文本编辑，不需要太复杂的功能

**Comment by purocean** [comment]
请参考 #95

**Comment by nicken** [comment]
原来如此 理解了 谢谢
