### ISSUE TITLE
如果要改造为对外的 Web 服务该怎么办呢？

### ISSUE THREAD

**Issue by komlei122** [purocean/yn#11]
----

如果要改造为对外的 Web 服务，本工具可能不太适合。或者请运行在可隔离控制的环境下。

----

大佬 关于这个有什么好的建议方案？假如md我都转成了html 有什么可以不用二次开发的服务？

**Comment by purocean** [comment]
因为本来这个就支持在浏览器中使用，所以在功能上直接对外服务基本没有问题。

我说的不太适合主要是考虑安全问题。访问没有认证校验（可使用 nginx 代理一层），应用开放程度太高，可以执行很多系统命令。前端为了拓展性也未作任何防护。其次是因为有部分功能依赖操作系统功能，比如打开文件目录功能，使用系统软件打开文件，这些功能都是在服务器上执行了。如果这些你都不在意，了解原理且可控，那放在服务器上跑对外提供服务没有问题。

这里有一个在docker中运行的 fork https://github.com/jasonhu/yn 你可以参考一下
