### ISSUE TITLE
能否实现窗口大小自定义

### ISSUE THREAD

**Issue by bwcsswcx** [purocean/yn#110]
功能很强大，有一个小建议，能否实现**源码区域**和**预览区域**的窗口可拖动，而非固定大小，如下面这种效果。谢谢。
![image](https://user-images.githubusercontent.com/50362405/159392996-760810f5-71fa-4814-8a2d-b252c5b99f51.png)

**Comment by purocean** [comment]
https://github.com/purocean/yn/commit/d6e6559bb0cf7f0d83f5e23abdcf75a1422cc9cd
