### ISSUE TITLE
功能建议：加密文档的密码使用统一的一份密码

### ISSUE THREAD

**Issue by bwcsswcx** [purocean/yn#111]
加密文档的密码都是创建`.c.md`的时候设置的，存在如下情况：
1. 创建多个加密文档，同一个加密密码，需要输入多次。   
2. 如果加密文档的密码泄露了，想修改密码也很麻烦，有多少加密文档，就需要修改多少次。

使用过一些云笔记，加密密码都是全局有效，设置一次，所有的加密文档都有同一个密码，如果想更改加密文档的密码也方便，就修改一次就可以了，感觉统一的密码比较方便，看作者大佬们怎么认为呢  (#^.^#)  ，谢谢。

**Comment by purocean** [comment]
可以看看这个 #68 ，现阶段项目技术基础还不成熟，会考虑这个功能

**Comment by bwcsswcx** [comment]
好的，谢谢
