### ISSUE TITLE
[ISSUE]: yank-note on server

### ISSUE THREAD

**Issue by yeehi** [purocean/yn#116]
**Describe the bug**
Yank note is a great desktop application. Where is the documentation showing how to provide yank-note on a server as a webpage, like the demo here:
https://yank-note.vercel.app/#/

**To Reproduce**
 Visit yn documentation
Search for instructions on how to create a yank-note webpage
-->

**Expected behavior**
Documentation provides an explanation of how to make a public instance of yn

**Additional context**
If there were a Docker image of yank-note, it would help people deploy yn on Cloudron: https://forum.cloudron.io/topic/6712/yank-note-yn-on-cloudron?_=1648400863177

**Comment by purocean** [comment]
Yank Note is positioned to run on the desktop, many functions rely on Electron, this requirement is not considered at present.

**Comment by AssKicker0214** [comment]
请问作者是否可以再考虑一下 @yeehi 的提议，个人觉得移植到前端以后一些功能无法实现也没问题，Demo 页面已经非常震撼了。YN 真的是一款超级好用的工具，无论怎样都非常感谢~

**Comment by tankgit** [comment]
@purocean 其实不一定要web版本，我觉得server端很重要，我们一个实验室可以部署一个没有GUI的server端，这样方便大家分享自己的yanknote给别人看（在别人没有安装yanknote的前提下），用自己的电脑起服务的话，IP一般不固定或无法访问

**Comment by purocean** [comment]
@tankgit 目前有分享预览功能（工具菜单中）。不过你说的固定ip这个得自己想办法了

![image](https://user-images.githubusercontent.com/7115690/181685306-5589a8e0-3c6a-4fc1-b7d0-29c9b7e3018f.png)

**Comment by tankgit** [comment]
> @tankgit 目前有分享预览功能（工具菜单中）。不过你说的固定ip这个得自己想办法了
> 
> ![image](https://user-images.githubusercontent.com/7115690/181685306-5589a8e0-3c6a-4fc1-b7d0-29c9b7e3018f.png)

我知道这个分享功能哈，我意思能否起一个linux端命令行界面的服务，这样相当于有个中央解析和存储分享文件的服务，然后任何人都可以通过浏览器直接访问被分享文件

**Comment by zelohon** [comment]
确实 强烈建议也有个[web](https://yank-note.vercel.app/#/) 的那个版本

**Comment by cbug404** [comment]
@zelohon 为了方便部署服务器，我这里做了个docker版本：https://github.com/cbug404/docker-yank-note
