### ISSUE TITLE
sequence 这个没有渲染哦

### ISSUE THREAD

**Issue by lq910304** [purocean/yn#117]
sequence 这个没有渲染哦

**Comment by purocean** [comment]
能否提供更多信息？

**Comment by keirosang** [comment]
![image](https://github.com/purocean/yn/assets/13990776/4385df1e-f58d-4fc5-b68f-ba20d23538cb)
![image](https://github.com/purocean/yn/assets/13990776/98ef487d-578e-4bed-8276-865edee1dc7f)

**Comment by purocean** [comment]
这是什么语法？目前应该不支持
