### ISSUE TITLE
[BUG]: 最新版本，导出功能，弹出的确定按钮点击无响应。macos12.3  arm64 

### ISSUE THREAD

**Issue by zhuyuanmin** [purocean/yn#119]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. v3.23.0]
 - OS: [e.g. macOS]

**Additional context**

**Comment by purocean** [comment]
导出的什么内容？什么格式？

**Comment by zhuyuanmin** [comment]
内容就是写的md内容。
无论选择哪种导出 按钮都是无响应

**Comment by zhuyuanmin** [comment]
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/23226876/160748612-e5a9982d-4544-48bc-a183-76dd2715ce6d.png">

**Comment by zhuyuanmin** [comment]
重启应用后恢复了

**Comment by purocean** [comment]
未能复现。打开控制台看看有没有相关报错呢？

**Comment by zhuyuanmin** [comment]
已知步骤：初次打开软件显示的说明.md关闭后，显示空白页，在此内容上编辑是无法导出。此场景是未配置本地仓库情况下。如上图的空白页所示

**Comment by zhuyuanmin** [comment]
此外，发现 软件无法使用 ctrl+c ctrl+v ctrl+x 三组快捷键，不知道是未实现还是如何？
<img width="399" alt="image" src="https://user-images.githubusercontent.com/23226876/160772096-416e9a0f-de3c-450b-8e2f-e5d1c16981d3.png">

**Comment by purocean** [comment]
快捷键都有，你的问题有点奇怪，如果方便可以扫项目说明文件下面的二维码加我微信详细说下

**Comment by purocean** [comment]
- 导出无反应是因为在空白页导出
- 快捷键无反应有点奇怪，有待找到真正的原因
