### ISSUE TITLE
[enhancement]: 增加菜单按钮

### ISSUE THREAD

**Issue by 442283045** [purocean/yn#120]
![image](https://user-images.githubusercontent.com/73371213/160869099-9bc288f4-1364-4596-8e56-77710846bf06.png)

在关闭侧边栏之后就找不到打开的方法了

**Comment by 442283045** [comment]
在我不小心关闭侧边栏之后就找不到打开的方法了

**Comment by purocean** [comment]
可以使用菜单或快捷键控制 

![image](https://user-images.githubusercontent.com/7115690/160959782-6525f325-0a3a-4e78-876b-8c12e71e8e37.png)

另外如果你进入了演示模式，可以按 ESC 退出
