### ISSUE TITLE
[BUG]: 部分情况下语法渲染不正确

### ISSUE THREAD

**Issue by DashChord** [purocean/yn#121]
**Describe the bug**
语法渲染不正确

**To Reproduce**
输入`**“测”**试`

**Expected behavior**
`**“测”**`被加粗

**Screenshots**
![image](https://user-images.githubusercontent.com/69285516/160889345-83eb55f0-380d-4d6f-9f70-b96b0ff3affe.png)

**Desktop (please complete the following information):**
 - Version v3.27.0
 - OS: Windows 11

**Additional context**
目前高亮和删除线语法也可以复现该语法错误

**Comment by purocean** [comment]
参考 https://ld246.com/article/1597581380183
