### ISSUE TITLE
代码块如何自动换行

### ISSUE THREAD

**Issue by bigkun** [purocean/yn#122]
有时需要记录公钥或license内容，复制到代码块中会显示为单个长行，是否有设置可以主动配置是自动换行或不换行

**Comment by purocean** [comment]
可以考虑在文档 Front Matter 中配置代码换行行为，感谢反馈

**Comment by purocean** [comment]
https://github.com/purocean/yn/commit/f646bfe8f21c812027e77e1fd09a91e4118e24bc

**Comment by purocean** [comment]
https://github.com/purocean/yn/releases/tag/v3.28.0
