### ISSUE TITLE
【功能请求】支持关闭编辑器小地图

### ISSUE THREAD

**Issue by yiyungent** [purocean/yn#124]
> 目前使用 Windows yn [v3.27.0](https://github.com/purocean/yn/releases/tag/v3.27.0)    
> 很棒的软件，感谢！

![image](https://user-images.githubusercontent.com/16939388/161547755-d9cb4755-7d63-414f-b289-0a0510b72f9c.png)

- 能选择关闭中间的小窗口预览
- 编辑区 与 预览区 中间线能够拖动 来改变两边区域宽
  - 这个已经有 issue 了 https://github.com/purocean/yn/issues/110

> 最左侧 文件树 区就可以拖动
![image](https://user-images.githubusercontent.com/16939388/161548041-53e916c8-aa8b-44e4-a154-1e455889d086.png)

**Comment by purocean** [comment]
https://github.com/purocean/yn/commit/e16441a26e8a37bcc7d6a9581be5d97078cce9e1

**Comment by purocean** [comment]
https://github.com/purocean/yn/releases/tag/v3.28.0
