### ISSUE TITLE
开机启动能否增加静默启动功能？

### ISSUE THREAD

**Issue by tanqimin** [purocean/yn#127]
开机启动增加静默启动，即不自动打开主窗体，自动最小化到系统托盘。

**Comment by purocean** [comment]
现在有开启自动启动功能，但是不是最小到系统托盘

考虑到现在的计算机关机次数较少，我觉得静默与否不是什么重要的事情，如果加上反而会让程序配置更加复杂，所以暂时不考虑了

**Comment by purocean** [comment]
https://github.com/purocean/yn/issues/270
