### ISSUE TITLE
[FEEDBACK]: Changelog Format

### ISSUE THREAD

**Issue by yeehi** [purocean/yn#128]
**Describe the bug**
Changelog Format Suggestion

**To Reproduce**

1. Go to '[keepachangelog](https://keepachangelog.com/en/1.0.0/)'
2. Compare and contrast format for current and suggested keep a changelog format
-->

**Expected behavior**
Documentation format is exemplary

**Additional context**
yank-note software is highly capable of producing beautiful documentation, and indeed it does look good. It might be worth assessing whether the formatting should conform with a standard.

**Comment by purocean** [comment]
Yank Note is not a library, The current way is more suitable. https://github.com/purocean/yank-note-extension use the better changelog.
