### ISSUE TITLE
[Feedback]: yank-note "Create New" document button

### ISSUE THREAD

**Issue by yeehi** [purocean/yn#129]
**Create New Document button is not apparent**

**To Reproduce**

**Expected behavior**
There is a "Create New" button, probably in the top-left
There is a recognizable icon to click for this frequently required task

**Additional context**
Perhaps right-clicking could bring up a dialogue of options including "create new" as a possibility...

**Comment by purocean** [comment]
Aways show create button on empty tree.

https://github.com/purocean/yn/commit/02bf0a8a6de088e35221a7bd4bf5090697e2f422
