### ISSUE TITLE
请问有在全仓库中查找字符串的功能吗？

### ISSUE THREAD

**Issue by yjy20170** [purocean/yn#13]
如题

**Comment by purocean** [comment]
你可以试试 ctrl + p 快捷键

**Comment by yjy20170** [comment]
谢谢~ 试了一下很好用，顺便想再问一个问题，Yank好像不支持用 [^footnote] 创建脚注，请问有替代方法吗？

**Comment by purocean** [comment]
> 谢谢~ 试了一下很好用，顺便想再问一个问题，Yank好像不支持用 [^footnote] 创建脚注，请问有替代方法吗？

脚注功能确实还待增强，接下来把这个功能加上吧

**Comment by yjy20170** [comment]
好的，期待！

**Comment by purocean** [comment]
@yjy20170 https://github.com/purocean/yn/releases/tag/v2.3.5 2.3.5 版本已加入脚注功能

**Comment by purocean** [comment]
https://github.com/purocean/yn/issues/86
