### ISSUE TITLE
[咨询]: 使用问题咨询

### ISSUE THREAD

**Issue by Darin726** [purocean/yn#131]
##### 问题 1
很喜欢 Yank Note "浏览器打开" 这个功能, 但发现有一个疑惑.

"浏览器打开" 只能通过 `localhost:3044` 打开, 无法通过 `ip:3044`打开; 譬如本机是 192.168.1.2, 无法通过 `192.168.1.2:3044` 打开; **如何可以通过 ip 的方式使用浏览器打开**

另外,快捷键是否可以自定义, 因为全局的 `CMD+ shift +B` 和浏览器打开书签栏的快捷键冲突了

#### 问题 2
`Yank Note` 支持两种付费模式, `AppStore` 和 软件内购的方式; 我理解如果通过 `AppStore` 来购买, 那么当前 `Apple ID`的设备都可以使用付费模式;

那么如果通过 `软件内购` 的方式购买
1. 是否只支持本机使用
1. 激活码可以激活多少台设备
1. 是否支持反激活

**Comment by purocean** [comment]
- 浏览器打开功能
为了安全性考虑，暂时只支持本机访问整个应用。你可以在设置中配置监听 `0.0.0.0`，但目前仅限于分享功能。不过从设计上，应用生成的 jwt token 是支持所有权限的，现在未放开。

- 快捷键
可以参考 #3 

- 激活
如果你要使用“浏览器中打开”功能，Mac App Store 中的版本是不支持的。参考：https://github.com/purocean/yn/issues/65#issuecomment-1065799677
商店版本的激活是跟着 Apple ID 走的，可以恢复购买，没设备限制，只要账户有就行。
GitHub 版本的激活是用激活码的，暂时没有设备限制，备份应用数据即可。真的掉了可以联系我恢复。
