### ISSUE TITLE
archlinux上终端打开的不对

### ISSUE THREAD

**Issue by Martinits** [purocean/yn#132]
用的是aur上有人打包的，不知是不是官方打包，https://aur.archlinux.org/packages/yank-note-bin
打开终端是sh，而不是我的login shell -- zsh。

**Comment by purocean** [comment]
要不试试在设置中自定义一下？

![image](https://user-images.githubusercontent.com/7115690/163322374-83c43b4a-c962-49ce-9011-6e08e53f76bd.png)
