### ISSUE TITLE
导出的pdf 分页处文字和图片会断开

### ISSUE THREAD

**Issue by Martinits** [purocean/yn#133]
![2022-04-14_14-15](https://user-images.githubusercontent.com/48900241/163326269-31bea988-674c-463a-b05c-90429fb97fd0.png)
![2022-04-14_14-21](https://user-images.githubusercontent.com/48900241/163326284-5453a31c-15ee-4930-8500-45b71ee76a15.png)
![2022-04-14_14-23](https://user-images.githubusercontent.com/48900241/163326292-6f7d30cb-1c30-4dc9-b7c6-725b6552749c.png)
不晓得是不是要设置什么？
还有就是有些图为啥空白这么大：
![2022-04-14_14-24](https://user-images.githubusercontent.com/48900241/163326296-8b6c9f09-973f-4e09-b412-14a0658e8706.png)

**Comment by purocean** [comment]
如果在实际使用中，你需要调整 PDF 的分页行为，可以试试 `new-page` 这个样式类。参考：https://github.com/purocean/yn/blob/develop/help/FEATURES_ZH-CN.md#%E5%85%83%E7%B4%A0%E5%B1%9E%E6%80%A7%E4%B9%A6%E5%86%99

**Comment by Martinits** [comment]
自动分页多好，一般来讲谁也不想断开吧哈哈
所以electron自带的不支持分页？

**Comment by purocean** [comment]
可以研究一下

**Comment by purocean** [comment]
我又看了一下，上面的容器块被断开是预期中的行为，因为容器内部文字可能会很多。然后后面空白很大正是图片尽量不被打断的逻辑在起作用。

因此，加一个元素不被打断的样式类可能会更好。使用 `page-break-inside: avoid;` 样式。

**Comment by purocean** [comment]
https://github.com/purocean/yn/commit/a1badccf94f5092c8e3ed05a8cbf5e5860736575
