### ISSUE TITLE
[BUG]: [Yank-Note 特色功能使用说明] 中 Draw.io 图形 和 Luckysheet 表格没有展示

### ISSUE THREAD

**Issue by GOWxx** [purocean/yn#134]
**问题描述**

Yank-Note 特色功能使用说明中 Draw.io 图形 和 Luckysheet 表格没有展示
该文件中预览模式下展示如下，这是预期行为吗？
![image](https://user-images.githubusercontent.com/12870715/163464998-a728c2bf-a4cd-4466-9176-934b1fe3ff94.png)
在主目录下也并没有 `./test.drawio` 和 `./test.luckysheet`  

**复现方法**

1. 打开应用主界面
2. 点击右下角帮助 - 特色功能说明
3. 划到 378行，看右侧渲染模式或演示模式下14 15点
4. 看到上面图中内容

 - Version [v3.28.0]
 - OS: [macOS 12.3.1]

**Comment by purocean** [comment]
嗯，确实是没加这两个示例，可以加上

**Comment by purocean** [comment]
https://github.com/purocean/yn/releases/tag/v3.29.0
