### ISSUE TITLE
[REQUEST]希望可以支持在Pandoc基于Markdown导出docx时支持PlantUML与drawio图像

### ISSUE THREAD

**Issue by FZerolight** [purocean/yn#135]
当前版本在基于Markdown导出DOCX时没有将PlantUML代码块与Drawio链接替换成相应的图形资源，导致最后生成的docx没有正确显示内容。

而基于渲染后的HTML导出DOCX时，虽然可以正确显示PlantUML与Drawio，但似乎对Latex公式的处理有一些小毛病：

Latex内容：
```latex
$$
\frac{(10*365*24*\frac{60}{5})}{32*32} \approx 1026
$$
```

Yank-Note渲染结果：
![image](https://user-images.githubusercontent.com/7200654/165009298-4638649b-cd89-4e09-a464-91c97410539c.png)

基于HTML渲染结果导出DOCX结果：
![image](https://user-images.githubusercontent.com/7200654/165009344-75fb75e0-91ed-44f7-857b-c249d9dd52eb.png)

以及，`.drawio.png`图像现在不会被drawio插件识别为drawio文件，看了下源码是硬判定的后缀，不知道是不是刻意设计的

**Comment by purocean** [comment]
1. 基于Markdown导出DOCX 还是不做更多工作了
1. 导出公式这里可以处理下
1.  .drawio.png图像现在不会被drawio插件识别为drawio文件 是刻意的，图片就是当图片渲染。如果要编辑可以在侧栏点击再编辑

**Comment by purocean** [comment]
https://github.com/purocean/yn/commit/2583f5f7b559d30605d9f665e4b6e0d9ac7a7a9c
