### ISSUE TITLE
[Doc]: 开发环境搭建手册的完善 

### ISSUE THREAD

**Issue by WangLaoShi** [purocean/yn#140]
很感谢 purocean 提供的 yn 这个小工具，尝试使用了几天，蛮好用的。

打算本地做一个简单的修改，发现竟然在 Readme.md 中没有关于开发环境的搭建的步骤。碰壁了不少之后，好不容易在 help 文件找到了 DEVELOP_ZH-CN.md 。但是也许，大概是官方的开发人员对 node 和包都很熟悉，或者本地的环境都很稳定了，也没有出现这样或者那样的问题，不知道一个新手搭建环境的痛苦。

所以打算 fork 一下这个项目，尽自己的能力去完善一下这个小文档。

**Comment by purocean** [comment]
可以尽量参照 CI 文件搞 https://github.com/purocean/yn/blob/develop/.github/workflows/release.yml
