### ISSUE TITLE
[功能实用]: 不支持 ctrl+f 搜索关键字

### ISSUE THREAD

**Issue by craca** [purocean/yn#150]
1、如果一个文档内容比较长，不能通过搜索关键字快速定位
2、编辑和预览使用不太方便，因为在视图显示太多选项，建议增加一个快捷图标功能，点一下切换预览或编辑

**Comment by purocean** [comment]
1. 查找文档内容暂时没有。作为替代方案，你可以在浏览器中使用（点击托盘/菜单栏图标 --> 浏览器中打开），使用浏览器的查找功能。以后看这个功能是否加上。
2. 你可以使用快捷键切换，如果不能满足你的需求，可以尝试自己写插件

**Comment by purocean** [comment]
1. 文档内搜索 https://github.com/purocean/yn/commit/badc9494cb4a0dd34e936129d6d25b68b6c74a40
2. 编辑预览切换可以使用快捷键+“编辑器预览互斥”
