### ISSUE TITLE
[BUG]:代码块无法正常执行Python代码，终端中却可以正常执行

### ISSUE THREAD

**Issue by small-universe** [purocean/yn#152]
**Describe the bug**

代码块无法正常执行Python代码，终端中却可以正常执行

**To Reproduce**

**Expected behavior**

**Screenshots**

![bug](https://user-images.githubusercontent.com/38489363/168801802-226c34ac-9f46-40c5-8299-a0ba60a61186.gif)

**Desktop (please complete the following information):**
 - Version: [3.30.1]
 - OS: [Windows10]
 - Python：3.8.10

**Additional context**

**Comment by purocean** [comment]
如果方便，可以加项目下面微信详细沟通一下

**Comment by huangqinjin** [comment]
`运行` 使用的是`python3`:
https://github.com/purocean/yn/blob/4cfd1acf0fa5de7f80f8e4129686a84a4b4c97bf/src/main/server/run.ts#L31

而 `在终端中运行` 使用的是 `python`:
https://github.com/purocean/yn/blob/4cfd1acf0fa5de7f80f8e4129686a84a4b4c97bf/src/renderer/components/Xterm.vue#L138

Windows 上应该没有 `python3.exe`, 在 Linux 上 `python` 默认是符号链接到 `python2.7`。

**Comment by small-universe** [comment]
应该是 @huangqinjin 这位老铁说的这个原因 @purocean

**Comment by purocean** [comment]
新的代码运行机制可以自定义命令了

**Comment by qq85715512** [comment]
````python
# --run--

def quick_sort(arr, i, j):
    if i < j:
        idx = get_index(arr, i, j)
        quick_sort(arr, i, idx)
        quick_sort(arr, idx + 1, j)

def get_index(arr, i, j): 
    tmp = arr[i]
    while i < j and tmp <= arr[j]:
        j -= 1
    arr[i] = arr[j]
    while i < j and arr[i] <= tmp:
        i += 1
    arr[j] = arr[i]
    arr[i] = tmp 
    return i

arr = [3,2,1,8,4,14]
quick_sort(arr, 0, 5)
print(arr)
```
`
python在执行代码时如果有缩进，貌似会报错：
<img width="879" alt="image" src="https://github.com/purocean/yn/assets/6128123/bec6637b-1b7f-4da0-a033-cfdeff58ed36">
