### ISSUE TITLE
[BUG]:插入图片是否存在缓存

### ISSUE THREAD

**Issue by lcl0512** [purocean/yn#154]
**Describe the bug**

我先再markdown插入图片，然后修改图片内容，markdown中图片没有改变
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. v3.23.0]
 - OS: [e.g. macOS]

**Additional context**

**Comment by pathing** [comment]
你可以看下设置里面"图片"一栏里面可以设置一个路径，一般插入图片后，图片会保存在这个路径

**Comment by sccuijian** [comment]
确实是这样。图片更新后，markdown中的图片还是显示原来的图片，需要重启软件才能生效。

**Comment by purocean** [comment]
你可以通过切换文件的方式来刷新图片，这个提交增加了刷新文档后也更新图片的功能
https://github.com/purocean/yn/commit/6b63c4aebf6b5348146aad286886f42213797075
