### ISSUE TITLE
【功能新增】目录的文件显示部分，增加对系统中新增文件的检查，减少刷新操作。

### ISSUE THREAD

**Issue by Yunis-YuanZhiyi** [purocean/yn#155]
如果使用Yank Note管理的文件夹下通过Git或者网盘的方式新增/删除文件，目前是必须通过手动刷新目录才能看到变化。
能否自动定期检测系统路径下是否有文件变化并显示，方便查看。

**Comment by purocean** [comment]
现在 Yank Note 增加了仓库索引功能，这个功能会监听当前仓库文件的文件变化。自动刷新功能[已安排](https://github.com/purocean/yn/commit/74e39e10886a407cf52ba1df9f758664ac60544d)，下个版本发
