### ISSUE TITLE
What's the killing feature of yn to Typora?

### ISSUE THREAD

**Issue by tristone13th** [purocean/yn#159]
Not suppose to be nit-picking, but I just wonder what's the killing feature of yn to Typora? As your know, Typora supports WYSIWYG, and it also supports Mermaid rendering, so what's the reason to migrate from Typora to this?

**Comment by purocean** [comment]
I haven't thought about making Yank Note a replacement for Typroa.

https://juejin.cn/post/7035276236473499661
