### ISSUE TITLE
[功能]增加latex公式补全

### ISSUE THREAD

**Issue by clq9920** [purocean/yn#160]
提供latex补全,或者用户代码片段之类的功能,对于公式渲染,是否有很好的性能?vscode里似乎更改一个公式,所有公式都会重新渲染(因为公式带编号?)快速的公式编辑和渲染是我寻找更好编辑器的理由

**Comment by purocean** [comment]
参考 https://github.com/purocean/yn/pull/153#issuecomment-1129481749
