### ISSUE TITLE
[BUG]: 双反斜杠渲染问题

### ISSUE THREAD

**Issue by 546454170** [purocean/yn#164]
**Describe the bug**
双反斜杠渲染问题:  “//young增长了1.5倍” 这段文字会自动加上链接，点击会弹出 “README_ZH-CN.md”

 - Version v3.30.0
 - OS: macOS

下图所示:

<img width="797" alt="bug" src="https://user-images.githubusercontent.com/106415707/172275732-b50b5844-481c-4140-afbc-b64745bf4a64.png">

**Comment by purocean** [comment]
这是把文本识别成了链接，上游解析器的问题。你可以加上空格避免识别

<img width="408" alt="image" src="https://user-images.githubusercontent.com/7115690/175813653-7f86cb62-abd8-47bd-83f1-eb0979fd8c73.png">

或者[设定文档参数](https://github.com/purocean/yn/blob/develop/help/FEATURES_ZH-CN.md#front-matter)来禁用链接解析

<img width="835" alt="image" src="https://user-images.githubusercontent.com/7115690/175813699-d86e9380-fdbf-4974-8ccd-866dc73c675a.png">
