### ISSUE TITLE
[BUG]: 打开终端error

### ISSUE THREAD

**Issue by Crackersssss** [purocean/yn#166]
version 3.31.0:

![image](https://user-images.githubusercontent.com/45088781/173535576-cff1d6aa-32ff-4b31-90cf-41f77e98eaf6.png)

仅更新了版本，未做任何设置上的改变，打开终端错误，旧版本打开没问题
version 3.30.1:

![image](https://user-images.githubusercontent.com/45088781/173536322-bf3eee69-cef6-4d44-8cef-520312e91af1.png)

**Comment by purocean** [comment]
重新跑了一下 CI，下载看看 https://github.com/purocean/yn/releases/tag/v3.31.0

**Comment by Crackersssss** [comment]
> 重新跑了CI，下载看看https://github.com/purocean/yn/releases/tag/v3.31.0

哎？可以了，为什么我直接更新不行？:)
