### ISSUE TITLE
[功能]请问有否考虑增加剪藏功能？

### ISSUE THREAD

**Issue by gray0128** [purocean/yn#167]
感谢作者！
请问是否有考虑增加浏览器的剪藏功能？

**Comment by purocean** [comment]
以前考虑过，但是这个工作量有些大，交互流程也没想好，以后再说吧。目前不考虑了。

**Comment by gray0128** [comment]
> 以前考虑过，但是这个工作量有些大，交互流程也没想好，以后再说吧。目前不考虑了。

chrome插件web clipper可以剪藏到github仓库，算了已经有解决方案了

**Comment by kimxwang** [comment]
> > 以前考虑过，但是这个工作量有些大，交互流程也没想好，以后再说吧。目前不考虑了。
> 
> chrome插件web clipper可以剪藏到github仓库，算了已经有解决方案了

请问是用什么方案解决的？

**Comment by gray0128** [comment]
> chrome插件web clipper可以剪藏到github仓库

**Comment by gray0128** [comment]
> > > 以前考虑过，但是这个工作量有些大，交互流程也没想好，以后再说吧。目前不考虑了。
> > 
> > 
> > chrome插件web clipper可以剪藏到github仓库，算了已经有解决方案了
> 
> 请问是用什么方案解决的？

chrome插件web clipper可以剪藏到github仓库
