### ISSUE TITLE
[BUG]: After updating to version 3.31.0, terminal open error occurs on Windows 10

### ISSUE THREAD

**Issue by boboboneX** [purocean/yn#169]
**Describe the bug**
After updating to version 3.31.0, Javascript error occurs when opening the termimal, both in the desktop app and the browser (MS edge).

**To Reproduce**
1. Open the main window
2. Open the terminal by clicking the terminal button in the bottom-right corner
3. Error message appears (screenshot below), and terminal stucks with no message

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/91120779/174201953-c2c11cf7-dab2-499f-bc26-afbd41df6561.png)

 - Version: 3.31.0
 - OS: Windows 10
 - Browser: desktop & edge

**Comment by purocean** [comment]
#166
