### ISSUE TITLE
emoji arrow 开头的8个方向显示异常

### ISSUE THREAD

**Issue by wumouse** [purocean/yn#174]
arrow 开头的8个方向 emoji：➡️⬅️⬆️⬇️↗️↘️↙️↖️。
在 app 编辑模式下只有上、下、左正常显示。
在预览中右也可以正常显示。
在 vs code 里输入这几个显示和上面编辑结果一样，上、下、左正常。

在浏览器中打开8个方向全部显示正常。

**Comment by purocean** [comment]
编辑器的问题目前不好处理
