### ISSUE TITLE
[BUG]:打不开terminal

### ISSUE THREAD

**Issue by Wanger-SJTU** [purocean/yn#175]
**Describe the bug**
最新版本安装以后打开终端失败。
**Additional context**

![image](https://user-images.githubusercontent.com/35162184/177440288-9cbc0240-b854-48cf-9e70-71b97b701897.png)

**Comment by purocean** [comment]
试试重新下载正式版安装，之前的包打得有问题

参考：https://github.com/purocean/yn/issues/169

**Comment by Wanger-SJTU** [comment]
还是这个问题，需要先卸载吗？我这边卸载了再安装也会这样

**Comment by purocean** [comment]
貌似和之前的问题不是同一个。你配置的终端程序是什么？

**Comment by Wanger-SJTU** [comment]
我这边默认的powershell。

**Comment by purocean** [comment]
我测试了，如果在设置中配错了shell程序，可能会导致这个问题
![image](https://user-images.githubusercontent.com/7115690/177959317-7225514a-7ada-4925-bd94-6267179c1732.png)
