### ISSUE TITLE
TOC可以自定义序号吗？

### ISSUE THREAD

**Issue by mengzc** [purocean/yn#18]
[toc]{type: "ol", level: [1,2,3]}
默认序列是
```
1.
    i.
        a.
        b.
    ii.
2.
3.
```
能修改成：
```
1
1.1
1.1.1
2.
2.1
2.1.1
2.2
```
这种吗？

想用来写手册，一般手册都是1.1.1这种序列的。

**Comment by purocean** [comment]
要不试试用无序列表，直接在标题中加编号

**Comment by purocean** [comment]
@mengzc TOC 标号已在 https://github.com/purocean/yn/releases/tag/v2.4.4 中更改，使用 `[toc]{type: "ol", level: [2,3]}` 试试
