### ISSUE TITLE
[功能建议] 文本编辑器加入自动换行

### ISSUE THREAD

**Issue by DawnMagnet** [purocean/yn#181]
建议可以给文本编辑器加一个自动换行的选择开关，这样不会出现如下图这种实际上很长但是只显示一行的情况

![image](https://user-images.githubusercontent.com/61567130/183292342-c4ac2c94-2006-41a6-bf22-5a78acc38c3b.png)

**Comment by purocean** [comment]
有这个功能， 看看”视图“菜单 https://github.com/purocean/yn/issues/146
