### ISSUE TITLE
[BUG]:drawio插入覆盖下面 内容，之前版本不会，图片悬浮在文档内容之上挡住了一大片

### ISSUE THREAD

**Issue by echowings** [purocean/yn#182]
**Describe the bug**

**To Reproduce**

RT

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. v3.23.0]
 - OS: [e.g. macOS]

**Additional context**

**Comment by purocean** [comment]
升级一下 Reveal.js 插件，这个插件之前有点问题

**Comment by echowings** [comment]
It works! Thanks!:)
