### ISSUE TITLE
[咨询] 该项目用的什么框架打包成桌面应用的？

### ISSUE THREAD

**Issue by ptko5** [purocean/yn#183]
1.该项目是怎么打包成exe的？用到的那些技术？
2.该项目是怎么打包成dmg的？用到的那些技术？
3.该项目是怎么打包成deb的？用到的那些技术？
4.有什么相关的打包成桌面应用的文档吗？
感谢！

**Comment by purocean** [comment]
主要技术是 electron。可以看看这个工作流文件 https://github.com/purocean/yn/blob/develop/.github/workflows/release.yml
