### ISSUE TITLE
[Feature Request]: 批量把文档中所有图片转成base64

### ISSUE THREAD

**Issue by winner106** [purocean/yn#193]
大佬，有些平台图片导入失败或者不能导入，需要转成base64才能粘贴，希望可以增加这个功能。可以是url转base64，或者相对路径图片转base64，如果能把base64代码折叠，或者像参考2那样放文章最后也不错喔

参考1：https://blog.csdn.net/gogoingstudy/article/details/119064231
参考2：https://blog.csdn.net/Yi_hua/article/details/116041312
参考3：https://gitee.com/fmtdjj/md_img2base64_project

![image](https://user-images.githubusercontent.com/50519642/188765713-f1e99793-d651-47ee-ba67-f3c58a7dcf42.png)

![image](https://user-images.githubusercontent.com/50519642/188774039-99fcfb73-0fbd-4f1f-b280-8c5c0ccef351.png)

**Comment by purocean** [comment]
试试这个功能 状态栏菜单->工具->复制内容。选择内联图片就可以了。只是没有压缩

<img width="484" alt="image" src="https://user-images.githubusercontent.com/7115690/188771397-cee6d815-75b9-4a59-b19b-9da279b9723b.png">

**Comment by winner106** [comment]
> 试试这个功能 状态栏菜单->工具->复制内容。选择内联图片就可以了。只是没有压缩
> 
> <img alt="image" width="484" src="https://user-images.githubusercontent.com/7115690/188771397-cee6d815-75b9-4a59-b19b-9da279b9723b.png">

看到了，我居然忽略了这个功能~
感谢大佬，如果能把引用外链的图片，复制时也能内联就太方便了！
