### ISSUE TITLE
[BUG]:有图片时编辑区和预览区滚动不同步

### ISSUE THREAD

**Issue by 71-MengYi** [purocean/yn#194]
如题，图片一多滚动就很难同步了，编辑区滚到底了，预览区还在中下的位置，很难追踪内容

**Comment by purocean** [comment]
https://blog-purocean.vercel.app/yank-note-04/ 可以先看看这个文章，目前还不太好搞

**Comment by purocean** [comment]
我单独试验了全是图片的文档，同步滚动行为还是比较符合预期的。你可以把文档源码贴出来看看吗？

**Comment by 71-MengYi** [comment]
我不知道怎么贴，我的文档是图文结合的。比如说我想编辑编辑区底部的一行文字，此时在预览区是看不到这行文字的。也就是说每当我想修改某行文字的时候，总需要花费一点时间在预览区寻找对应的部分，才能看到渲染后的效果，而代码与渲染后效果差距太大，导致每次都需要反应一段时间。

提个建议您看是否合适。就是像在预览区点击某行会跳转编辑区一样，在编辑区点击某行，预览区也会把对应的那行内容移动到与焦点齐平的位置。或者把这个做成快捷键响应也可，这样可以避免逻辑混乱

2022年9月15日 14:15，洋子 ***@***.******@***.***>> 写道：



我单独试验了全是图片的文档，同步滚动行为还是比较符合预期的。你可以把文档源码贴出来看看吗？

**Comment by purocean** [comment]
你用的是 base64 图片吗？不过聚焦预览行这个功能我觉得可以有

**Comment by purocean** [comment]
已添加 `Alt/Option + L` 快捷键聚焦预览所在行 https://github.com/purocean/yn/commit/27af3631b410723e04070b8f625da4a353f8d661

**Comment by purocean** [comment]
这个功能目前还没发布。如果你想体验，可以下载 pre-release 版试试

**Comment by 71-MengYi** [comment]
我不知道base64，我是右键拷贝图片再直接粘贴进去的。我没太仔细研究图片格式这些🧐

2022年9月15日 17:08，洋子 ***@***.******@***.***>> 写道：



你用的是 base64 图片吗？不过聚焦预览行这个功能我觉得可以有
