### ISSUE TITLE
[BUG]:搜索内容无法使用

### ISSUE THREAD

**Issue by simake2017** [purocean/yn#196]
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/31234273/190569709-b91ff2c1-cb17-4863-8315-dd67fb02cd52.png">

什么都搜索不出来

**Comment by purocean** [comment]
你看一下当前打开的是什么仓库。搜索范围仅限于当前仓库，不包括打开的文件

**Comment by simake2017** [comment]
当前仓库 都搜索过了，也搜索过字符 ，但是都没有搜索出来 我是mac m1
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/31234273/190571316-ae464b12-f889-42ae-9ed2-1c9a82976bc3.png">
我搜索一个spring  都没有任何内容

**Comment by simake2017** [comment]
spring 都很多的

**Comment by purocean** [comment]
我这里测试正常。如果方便加我微信详细聊一下吧，README 下方有二维码

**Comment by simake2017** [comment]
添加了

**Comment by purocean** [comment]
目前只能搜索 markdown 文件
