### ISSUE TITLE
[Feature Request]: 可以支持隐藏目录和文件不在左边文件树中不显示吗？

### ISSUE THREAD

**Issue by dekit-cn** [purocean/yn#197]
[Feature Request]: 可以支持隐藏目录和文件不在左边文件树中不显示吗？
有些目录和文件不需要显示，建议左边文件树不要显示隐藏文件。

**Comment by purocean** [comment]
这个需求已经记录在案，未来会加的

**Comment by Flow-sandyu** [comment]
对啊，像 file 这种文件夹一般不会打开，还有 pdf，xmind 等文件。希望能手动设置隐藏除 .md 之外的文件，也可以手动显示其它文件。

**Comment by purocean** [comment]
https://github.com/purocean/yn/commit/25ca882c03ca1e3cb248529617d7aa67b254bea6
