### ISSUE TITLE
[BUG]:在空白页写东西后，点击某个md文件，空白页会被直接覆盖

### ISSUE THREAD

**Issue by qingmu-z** [purocean/yn#201]
在空白页写东西后，点击某个md文件，空白页会被直接覆盖，不会保存。
写了半天的文档，我哭了![005936BE](https://user-images.githubusercontent.com/74592476/191043133-bf92dd51-0a55-4d1a-9368-a2950efe8fc9.png)

**Comment by 71-MengYi** [comment]
这个不是新建了文件才能写东西吗？你在空白页怎么写，如果是新建了文件再写，可以随便切换都不愁

**Comment by qingmu-z** [comment]
第一次打开软件或者把标签页都叉掉后，是有一个空白页的。好像以前的版本是没有的，新版本是有空白页的。

**Comment by purocean** [comment]
还是加个关闭保存提示吧

**Comment by purocean** [comment]
https://github.com/purocean/yn/commit/5e81a0cd74f80f37c71857d58a8327552e8ddfe4
