### ISSUE TITLE
[BUG]: group#group-item 标签内容使用代码块, 展示内容溢出容器

### ISSUE THREAD

**Issue by BOFA1ex** [purocean/yn#204]
**Describe the bug**
见标题，如图所示

**To Reproduce**
```
:::: group 
::: group-item *Usage
\```java
....
\```
:::
::: group-item Cypher

:::
::: group-item nGQL

:::
::::
```

**Expected behavior**
代码块展示内容不溢出group当前容器.

**Screenshots**
![image](https://user-images.githubusercontent.com/30573693/191915556-8cb67942-ad8f-4da5-9752-01cd8726eb1b.png)

**Desktop (please complete the following information):**
 - Version v3.36.1
 - OS: macOS
 - Browser chrome

**Comment by purocean** [comment]
经过排查，是主题的问题

**Comment by purocean** [comment]
请到这里反馈 https://github.com/Yannnser/yank-note-theme
