### ISSUE TITLE
[BUG]: group-item 不显示`<`&`>`括内内容

### ISSUE THREAD

**Issue by BOFA1ex** [purocean/yn#205]
**Describe the bug**
见标题，如图所示

**To Reproduce**
source: 
![image](https://user-images.githubusercontent.com/30573693/191916690-aa932dfd-ca96-4ea5-8284-35a1e96266d1.png)

preview:
![image](https://user-images.githubusercontent.com/30573693/191916756-922808be-9e34-4886-b5df-11dafbfba859.png)

**Desktop (please complete the following information):**
 - Version v3.36.1
 - OS: macOS
 - Browser chrome

**Comment by purocean** [comment]
用围栏的形式来包裹代码最好。尖括号会被解析为 html

~~~markdown
```
这里面是代码
```
~~~
