### ISSUE TITLE
[BUG]: 表情符号未能正确显示 和 标题不能正确跳转

### ISSUE THREAD

**Issue by Flow-sandyu** [purocean/yn#207]
**Describe the bug**

1. 在 typora 写的表情符号，在 yanknote 里打开表情符号未能正确显示
2. 在 typora 写的标题链接跳转，在 yanknote 里打开链接不能正确跳转
下图有说明
 
第二个 bug 应该是不同软件语法识别不一样，其实影响的就是我这种同时用 typora 和 yanknote 的用户

**Screenshots**
对比两个软件的
![image](https://user-images.githubusercontent.com/72751523/192076871-d0a6f771-c6ba-4325-8b0d-9a6dcc691b0a.png)
![image](https://user-images.githubusercontent.com/72751523/192076908-47b011eb-79c1-447b-a122-e2c179b6ef5a.png)

**Comment by purocean** [comment]
https://github.com/purocean/yn/releases/tag/v3.38.0 已添加 emoji 解析，界面被遮挡问题也解决了
