### ISSUE TITLE
[Feature Request]: 几个功能建议

### ISSUE THREAD

**Issue by Flow-sandyu** [purocean/yn#208]
- 我是一个同时用 typora 和 yanknote 的用户。用我之所以用同时 typora ，有几个原因，同时希望 yanknote 能增加这些功能

    - 第一个原因是 typora 可以边输出边显示，节省屏幕空间，希望 yanknote 能加这个功能，能选择可以边输出边显示的模式
    - 第二个原因是 typora 可以在目录视图下，通过拖拽文件来移动文件。而 yanknote 需要自己手动改路径
    - 第三个原因是 typora 可以把文件中所有本地图像一键上传图床
        -  ![image](https://user-images.githubusercontent.com/72751523/192078267-9ca5b4fe-23a9-4173-9cd7-2bd9307928c4.png)
    - 第四个原因是 typora 的目录视图下，可以折叠标题
        - ![image](https://user-images.githubusercontent.com/72751523/192078449-bae07a10-442a-45b0-ab3f-8ee98eb2d148.png)
 

- 关于其它建议
   - 我希望在目录视图下，希望能有重命名，删除，复制粘贴，新建文件夹和 markdown 文件的快捷键功能（比如Windows 的文件资源管理器里，F2 是重命名，Delete 是删除，然后 Ctrl + Shift + N 新建文件夹，Ctrl +  N 新建 markdown 文件），并能多选文件进行删除，复制粘贴。
     - 当然有些功能我也可以打开文件资源管理器做些操作，所以大部分建议也不是刚需
     - 但我觉得重命名，新建文件夹和 markdown 文件的快捷键挺实用的，可以减少不少鼠标操作
  - 希望能用快捷键来切换文件视图和目录视图，并在这两个视图里可以用键盘上下键选择指定的文件或目录，并能进入编辑窗口（写笔记的窗口），后续还可用快捷键把光标移动到侧边栏的窗口
     - 比如我用 alt + q 是切换到侧边栏窗口的目录视图，alt + w 切换到文件视图，切换后，光标在各个文件上，我可以通过上下键选择指定的文件或目录，并结合重命名，删除，复制粘贴，新建文件夹和 markdown 文件的快捷键功能进行文件操作，然后 可以通过shift + esc 把光标移动到编辑窗口。
     - 灵感来自 idea 的使用，它可以单用键盘就完成窗口切换，新建文件，删除等功能
  - 关于光标移动，我希望我按下  Ctrl + 1 切换窗口后，光标能显示到窗口里，而不需要用鼠标去点。

**Comment by purocean** [comment]
感谢建议

第一点，目前应该是不会考虑的，更多可以看看 https://blog-purocean.vercel.app/yank-note-01/ 
第二点，第四点和其他建议，这些体验都比较重要，要一步一步来。比如目录，目前实现就很朴素，还是最初版本的方案（参考上面文章），后面会慢慢优化。
第三点，已有人反馈。我想等到“上传器”相关 API 成熟后，把 Picgo 抽出为一个拓展再做
