### ISSUE TITLE
[BUG]:代码补全的界面在边界时会被遮住

### ISSUE THREAD

**Issue by Flow-sandyu** [purocean/yn#209]
**Describe the bug**
如图，代码补全的界面里，标题只显示了一部分。如果这个界面在边界处能动态调整就好了

**Screenshots**
![image](https://user-images.githubusercontent.com/72751523/192154337-a4c77c17-6e56-4b66-8d62-f3917aec3c85.png)

**Comment by purocean** [comment]
你目标文件是什么？可以贴出来看空吗？我测试没问题

**Comment by Flow-sandyu** [comment]
我重新测试了一下，代码补全的界面 应该是**被预览窗口遮住**了

目标文件名是
![image](https://user-images.githubusercontent.com/72751523/192194044-d1a67381-d793-4c30-acef-3619ad554e2c.png)


代码补全的界面 应该是**被预览窗口遮住**了，如下图
![image](https://user-images.githubusercontent.com/72751523/192193431-443e17af-0941-438d-bd4b-ac996324abf8.png)


同样情况没由预览窗口
![image](https://user-images.githubusercontent.com/72751523/192193226-87cd54b6-af7c-46ca-be00-cb50166a0279.png)

**Comment by Flow-sandyu** [comment]
还有一个建议，关于给图片插入有序列表或无序列表时，位置会出现偏差。如下图，我更希望有 typora 这种效果

![image](https://user-images.githubusercontent.com/72751523/192199037-6fc92a92-fabc-4e54-8344-97e3578c175a.png)

![image](https://user-images.githubusercontent.com/72751523/192199133-aecb8d25-2f7e-4600-9ebd-ce92ab5eec3e.png)

关于对我的影响：
  我做笔记的一种常用方式便是 截图配自己的文字，当长篇的截图+文字出现时，yknote 这种情况，看图片的序号会看的有点难受

**Comment by purocean** [comment]
代码补全展示不完全问题：https://github.com/purocean/yn/commit/59dd5a23912519bfcdab1ed92c0fa2f880172467
自动识别块元素图片：https://github.com/purocean/yn/commit/b3d978da75180643caf63e8ab30ca46862450081
