### ISSUE TITLE
[请教]:

### ISSUE THREAD

**Issue by PowerDi** [purocean/yn#211]
笔记功能特征设计的理念真的太棒了。苦寻各种软件终于有眼前一亮的感觉，一方面非常希望关注量能更多更多，一方面又担心激增的人数会影响你的开发精力。

使用感觉非常好，有一点疑问想请教下，目前很多笔记都采用所见即所得的模式，作者是怎么看待这种模式的呢？从我的体验上来说单栏就能直接看效果的会简洁更多

**Comment by purocean** [comment]
这篇文章我写了我对所见即所得的态度 https://juejin.cn/post/7035276236473499661
