### ISSUE TITLE
[改进建议]建议预览窗口的标题能够自动加上序号

### ISSUE THREAD

**Issue by 71-MengYi** [purocean/yn#214]
因为目前来说只有一二三级标题视觉上区别比较大，然而多个标题挤在一起时仍存在难以分辨的情况，尤其是往后的更多子标题区别很小，很拿分辨从属于哪一个大标题。能否在渲染时自动加上序号，以便分辨。

**Comment by purocean** [comment]
这个功能有了，参考文档 front matter 章节 https://github.com/purocean/yn/blob/develop/help/FEATURES_ZH-CN.md#front-matter

**Comment by vivio325** [comment]
> 这个功能有了，参考文档 front matter 章节 https://github.com/purocean/yn/blob/develop/help/FEATURES_ZH-CN.md#front-matter

这个功能中，h1级标题不会自动编号

**Comment by purocean** [comment]
一篇文档中，H1标题不应当有多个
