### ISSUE TITLE
[BUG]:创建/重命名文件夹无法输入名称

### ISSUE THREAD

**Issue by WenzhiShao** [purocean/yn#215]
如题

**Comment by purocean** [comment]
我测试了没问题，可以录个屏看看。

**Comment by WenzhiShao** [comment]
只出现了那一此，场景：当我创建了一个库，删除了另外一个库，之后创建了一个父目录，再其下创建子目录后，可以删除默认文件夹名但是无法输入，中英文输入法都不行。使用默认名创建后重命名也是一样。当我重启了yank后恢复正常了。不确定是否为可复现的。
