### ISSUE TITLE
[BUG]:关于空链接/无效链接的产品业务逻辑建议

### ISSUE THREAD

**Issue by WenzhiShao** [purocean/yn#216]
我发现点击没有实际/有效链接的链接后，会再此打开yank。这个我不太能理解，我觉得这里应该是哪儿也不跳转，或者提示链接无效似乎更符合用户逻辑。
如图，绑定摄像机还没有给链接地址
![image](https://user-images.githubusercontent.com/47174095/195857666-c2d46068-0953-4c9f-a734-85c5a97c8f58.png)
当点击后，又打开了一个yank
![image](https://user-images.githubusercontent.com/47174095/195857842-bc896b1f-2007-4cd8-8496-9a8ffd1e1420.png)

**Comment by WenzhiShao** [comment]
不好意思，不是bug，应该视为改进，使用点太快了，忘记修改

**Comment by purocean** [comment]
https://github.com/purocean/yn/commit/96e05e19696eb2f9b013c9977723de966c2c03f0
