### ISSUE TITLE
[BUG]:更新后安装报错

### ISSUE THREAD

**Issue by Baldman-JYH** [purocean/yn#220]
**Describe the bug**
在2022-11-02 打开后提示更新，从 **3.40.3-》3.41.0** 更新后安装时报错。

**To Reproduce**
1.打开软件。
2.提示更新，选择下载。
3.下载后安装时报错。

**Screenshots**
![image](https://user-images.githubusercontent.com/63494528/199374441-0127d863-aea1-4fe2-82d6-c98b00efea6d.png)

**Desktop (please complete the following information):**
 - Version 3.40.3
 - OS: win10 企业版 LTSC 21H2

**Comment by purocean** [comment]
报什么错？
