### ISSUE TITLE
[BUG]:文件排序BUG

### ISSUE THREAD

**Issue by WenzhiShao** [purocean/yn#222]
**Describe the bug**

**To Reproduce**
经过测试发现排序不是按照创建顺序排序的，其顺序测试了好几个也没发现其规律：
按1 2 3创建
![image](https://user-images.githubusercontent.com/47174095/200098004-d7248f81-a71c-40c8-8eae-64dce590f095.png)
按你 我 他的顺序创建
![image](https://user-images.githubusercontent.com/47174095/200098039-71885e32-27cb-4d1b-8f76-c3cf7e5f1422.png)

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. v3.23.0]
 - OS: [e.g. macOS]

**Additional context**

**Comment by purocean** [comment]
重复
