### ISSUE TITLE
[功能需求]偶尔需要在移动端（平板手机）查看笔记，能否提供一键导出所有笔记的功能

### ISSUE THREAD

**Issue by 71-MengYi** [purocean/yn#223]
[功能需求]偶尔需要在移动端（平板手机）查看笔记，能否提供一键导出所有笔记的功能
因为有时候上课，只带平板和手机，想看笔记的时候是看不到图片的

**Comment by purocean** [comment]
你可以使用云盘，如 iCloud 同步，然后随便找个 markdown 编辑器就能打开了。
