### ISSUE TITLE
表格适配问题

### ISSUE THREAD

**Issue by ChaWanerTT** [purocean/yn#224]
表格显示不好

<table >
	<tr>
		<td rowspan="3">Throwable</td>
		<td colspan ="2">Error</td>
	</tr>
	<tr>
		<td rowspan = "2">Exception</td>
		<td>RuntimeException</td>
	</tr>
	<tr>
		<td>非RuntimeException</td>
	</tr>
</table>

**Comment by purocean** [comment]
具体描述下？

**Comment by ChaWanerTT** [comment]
单元格合并&nbsp; colspan 和&nbsp; rowspan的效果显示不出来




嘘……给你一颗花生糖
***@***.***



&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "purocean/yn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月9日(星期三) 上午9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [purocean/yn] 表格适配问题 (Issue #224)





 
具体描述下？

**Comment by purocean** [comment]
我测试没能复现。如果你用的是老版本，请升级一下
![image](https://user-images.githubusercontent.com/7115690/200723143-71531615-6805-4ae3-8485-f6ade8e6dbcf.png)
