### ISSUE TITLE
是否有考虑增加同步服务器?

### ISSUE THREAD

**Issue by txchen** [purocean/yn#230]
感谢开源, 编辑器相当好用! 
想请问一下有没有考虑做同步服务器, 这样手机端和桌面端可以互相同步.

**Comment by purocean** [comment]
目前不考虑，你可以使用云盘代替

**Comment by northword** [comment]
@purocean 感谢开源！
请问未来有考虑支持 WebDav 嘛？很多云盘手机端并不是直接下载到本地的（比如 OneDrive 就需要用 Folder Sync ）
