### ISSUE TITLE
[BUG]: 文本过长，不会换行

### ISSUE THREAD

**Issue by TrumanDu** [purocean/yn#231]
**Describe the bug**

![image](https://user-images.githubusercontent.com/16727775/204261049-720e9e6b-036b-49cc-a2b7-38acc6beda70.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. v3.23.0]
 - OS: [e.g. macOS]

**Additional context**

vs code 中显示如下：
![image](https://user-images.githubusercontent.com/16727775/204261225-98295135-e3d6-437e-b1af-bdb487edb4e3.png)

从用户角度来说，控制编辑器的宽度，用户体验会更好一些

**Comment by purocean** [comment]
试试这个功能 
![image](https://user-images.githubusercontent.com/7115690/205559714-5d9d8eef-e5e9-4b9f-9ab8-a37299876a43.png)
