### ISSUE TITLE
[BUG]:文章内锚点标题带有中文和英文的情况， 生成PDF后锚点失效

### ISSUE THREAD

**Issue by LucasZhanye** [purocean/yn#233]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. v3.23.0]
 - OS: [e.g. macOS]

**Additional context**

当标题名称为中英文混合的情况，生成pdf后锚点无法正常跳转，点击无效

**Comment by purocean** [comment]
锚点是自己写的还是 toc 生成的？

**Comment by LucasZhanye** [comment]
> 锚点是自己写的还是 toc 生成的？
文章内部跳转的，使用[]()，自己写了标题，然后输入#后弹出的标题列表，点击选择的。
如下图
![image](https://user-images.githubusercontent.com/103245663/205225987-acc49c84-eed2-4062-b6a0-cdab5f76d558.png)

**Comment by LucasZhanye** [comment]
> 锚点是自己写的还是 toc 生成的？
而且刚刚发现，不只是中英文，其他字符也不行，比如我 发布/订阅，中间多一个斜杠也是不可以的

**Comment by purocean** [comment]
已修复，下个版本发 https://github.com/purocean/yn/commit/05cfe0681d4d61114e8e6ae75e638bf92c154003
