### ISSUE TITLE
Markdown and code block font config requirement

### ISSUE THREAD

**Issue by raven2cz** [purocean/yn#236]
I tried yn yesterday and today. I'm comparing notable vs yn. Main problem which I have is not good anti-aliasing markdown preview fonts. Sometimes it is very ugly on 4k. In configuration, there is possibility to change font for editor only. Editor has good font, I need to change font for rendered page, and mainly for code blocks. Is there some configuration file to change it? 
Similar is bad rendering of code blocks, the colors are faded and text not good readable.
In addition, in code blocks, the correct highlighting is applied in the editor, but not applied for rendered page.
Platform Linux Arch 64bit.

I try to attach screenshot.
![preview-font-config-req](https://user-images.githubusercontent.com/20504243/206401109-59b3986c-547b-4a02-bff3-7fd703c9ce4f.png)
![preview-font-config-req-2](https://user-images.githubusercontent.com/20504243/206401390-af224f86-c936-4da4-bdac-332dc69c0253.png)

**Comment by purocean** [comment]
Please provide your OS。You can custom css to override font.

**Comment by raven2cz** [comment]
@purocean Thanks for answer. It works!
* Is it possible to change the font of top tabs and left files list?
* About code block highlighting for `shell`. The code is very nicely highlighted in the editor, but almost nothing is highlighted in markdown preview code block. I tried `bash`, but it is very similar. Is it possible to improve this?

**Comment by purocean** [comment]
> @purocean Thanks for answer. It works!
> 
> * Is it possible to change the font of top tabs and left files list?
> * About code block highlighting for `shell`. The code is very nicely highlighted in the editor, but almost nothing is highlighted in markdown preview code block. I tried `bash`, but it is very similar. Is it possible to improve this?

1. custom css support change workbench styles
2. It's on record

**Comment by purocean** [comment]
Yank Note use prismjs instead of highlight.js, maybe better. https://github.com/purocean/yn/commit/63fbf473cf973a26bc690b634ffcc6c8753532bd
