### ISSUE TITLE
[BUG]:编写的一个小问题

### ISSUE THREAD

**Issue by marvin-min** [purocean/yn#238]
**Describe the bug**
在某些情况下，因为窗口大小的原因, 我把内容滚动到最后一行，加入有20行，我继续输入的话，会自动把最后一行滚动到中间。

**To Reproduce**
1. 新建一个文件
2. 写入好几行内容,如下图
<img width="369" alt="image" src="https://user-images.githubusercontent.com/767117/207999418-6a693643-73b6-4beb-92bf-8d96ad97a11d.png">
3. 滚到第最后一行继续写
<img width="380" alt="image" src="https://user-images.githubusercontent.com/767117/207999419-64130def-738b-4a70-8b9a-fb08cec76afc.png">
4. 然后就会被滚回到
<img width="375" alt="image" src="https://user-images.githubusercontent.com/767117/207999534-41ab726f-1b3a-4619-82a9-57bdf415d29e.png">

**Expected behavior**
不要滚动回去。

**Desktop (please complete the following information):**
 - Version [e.g. v3.46.0]
 - OS: [macOS]
 - Browser [chrome, safari]

**Comment by purocean** [comment]
你看看是不开启了打字机模式

<img width="217" alt="image" src="https://user-images.githubusercontent.com/7115690/208221240-30c584c1-7472-4a09-864d-2c0419870e71.png">

**Comment by marvin-min** [comment]
果然如此。感谢~
