### ISSUE TITLE
[BUG]: Yank Note always runs on system startup and there's no way to turn it off

### ISSUE THREAD

**Issue by Rezonansowy** [purocean/yn#242]
**Describe the bug**

Yank Note always runs on system startup and there's no way to turn it off

**To Reproduce**

1. Turn on the OS.
2. Experience the unexpected launch of Yank Note during the system startup.

**Expected behavior**

Yank Note doesn't run on system startup unless it is manually set by the user.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - Version: 3.47.0 (MAS)
 - OS: macOS Monterey (12.6.1)
 - Browser: N/A

**Additional context**

N/A

**Comment by purocean** [comment]
Please check this
![image](https://github.com/purocean/yn/assets/7115690/a60defad-ab55-4b79-ae23-c763982516a8)

**Comment by Rezonansowy** [comment]
Thank you, @purocean, for letting me know about this. I believe this is not the way a user-friendly setting should work like. For all this time, I was unaware that such an important setting like autostart at login will be only available when a user finds the app icon buried among a dozen of other apps in the system tray. Also, does the app follow the system "open at login" setting or does it some other way? This setting should be clearly available within the app's setting window. Otherwise, this is not really user-friendly. I would strongly suggest considering the above observations and implementing appropriate changes. Thank you for reviewing this feedback.
