### ISSUE TITLE
[BUG]: error "failed to parse path". Could no delete folder with a space in end 无法删除以空格结尾的文件夹

### ISSUE THREAD

**Issue by linweilin** [purocean/yn#244]
**Describe the bug**

can make the directory end with a space, but it can not be deleted. Only to be renamed end with non-spaces,  it can be deleted.

**To Reproduce**

**Expected behavior**

the folder can be deleted.

**Screenshots**

error"failed to parse path"

**Desktop (please complete the following information):**
 - Version [e.g. v3.47.0]
 - OS: Win11

**Comment by purocean** [comment]
使用新版看看，前面几个版本修复了一下
