### ISSUE TITLE
[feature]:希望添加vim按键功能

### ISSUE THREAD

**Issue by Free-Aaron-Li** [purocean/yn#250]
使用vim方式能够快速显著的提高开发效率，希望能够实现该功能。
如果开发时间有限，哪怕只是实现简单的移动、模式切换都行。
从obsidian过来，需要大量使用鼠标完成对我来说太麻烦了。

**Comment by purocean** [comment]
可以安装插件实现 https://github.com/zhyipeng/yank-note-extension-vim-mode/
