### ISSUE TITLE
[BUG]:plantUML support missing, why?

### ISSUE THREAD

**Issue by jiangjianbo** [purocean/yn#251]
**Describe the bug**

原来的 ```plantuml 块中的内容可以转换成图片，但是现在该功能升级后就丢失了。

**Desktop (please complete the following information):**
 - Version [v3.50.1]
 - OS: [macOS]
 - Browser [chrome, safari]

**Additional context**

**Comment by purocean** [comment]
你可以贴上源码和截图

**Comment by purocean** [comment]
这个功能新版已支持
