### ISSUE TITLE
[问题]:mac中环境变量应该怎么配置？格式应该怎么写

### ISSUE THREAD

**Issue by 71-MengYi** [purocean/yn#254]
PYTHONPATH= /usr/bin/python3
python =  /usr/bin/python3
python: ' /usr/bin/python3'
python=' /usr/bin/python3'
PATH =  /usr/bin/python3
PATH: ' /usr/bin/python3'
PATH=' /usr/bin/python3'
extPATH =  /usr/bin/python3
extPATH: ' /usr/bin/python3'
extPATH=' /usr/bin/python3'

我尝试了这么多个一个都没中啊

**Comment by purocean** [comment]
首先运行命令确定 python 在哪
```
@~> which python3                                                                                                (base) 
/opt/homebrew/anaconda3/bin/python3
```

然后配置环境变量
```
PATH: /opt/homebrew/anaconda3/bin/
```

最后在笔记中写入

```py
# --run--
print('HELLOWORLD')
```
