### ISSUE TITLE
【pandoc导出增强】希望 yn 的pandoc导出，支持绑定word模板中自定义的样式

### ISSUE THREAD

**Issue by aiyou9** [purocean/yn#258]
在工作中，有一些公司，以及学校中，最终提交版本，还是以word的格式进行的。一般都有特定的模板，比如学生的毕业论文，sci论文投稿，还有公司的内部报告，都是会有word模板的，一般都是固定的大纲，然后大纲每个部分，在word中会有很多自定义样式。

极端的例子比如：MDPI期刊出版社的模板： https://www.mdpi.com/journal/forests/instructions
[forests-template.docx](https://github.com/purocean/yn/files/11302894/forests-template.docx)

![image](https://user-images.githubusercontent.com/15712822/233821535-db40206d-5acf-4ebf-a315-80f30532efc8.png)

从上面，可以发现，文章都是固定的大纲，然后每一个部分，在word模板的样式库里，出版社都设置了一个对应的word样式。我想，在公司中，一些汇报，可能也是这种情况。

以这个docx模板，进行pandoc的绑定
https://stackoverflow.com/questions/70513062/how-do-i-add-custom-formatting-to-docx-files-generated-in-pandoc
官方文档中的说明：
 [Pandoc User's Guide - Custom Styles](https://pandoc.org/MANUAL.html#custom-styles)

JavaScript代码使用pandoc-filter库：

```javascript
const pandoc = require("pandoc-filter");

const customStyles = {
   //"Heading 1": "一级标题",
      "Heading 1": "My Heading 1"
    "Heading 2": "二级标题",
    "Heading 3": "三级标题"

};

function applyCustomStyle(style) {
    return (key, value, format, meta) => {
        if (key === "Header" && value[0] === style) {
            value[1] = { ...value[1], "custom-style": customStyles[style] };
        }
    };
}

const filters = Object.keys(customStyles).map(applyCustomStyle);

const options = {
    to: "docx",
    output: "output_file.docx"
};

pandoc.stdio(options, ...filters);
```
请注意，在使用这些代码时，您需要根据具体的输入和输出格式以及自定义标题样式进行修改和调整。
比如，在 Word 中将自定义标题样式与 Pandoc 绑定后，您可以通过在样式名称前加上 custom-style- 来在 Markdown 文本中使用相同的自定义样式名称。例如，如果您在 Word 中有一个名为“My Heading 1”的自定义样式，您可以像这样在 Markdown 文本中使用它：

在markdown中
```markdown
# My Custom Heading 1 {#custom-style-My Heading 1}
```

此外还可以使用lua脚本语言进行扩展
https://github.com/pandoc/lua-filters
https://github.com/pandocker/pandocker-lua-filters

为 yn 的便捷页面上，每一个行（块）绑定对应的样式，如果能够读取word模板的样式名，提供给用户，将样式绑定到块
可以把绑定，渲染在块后面，平时隐藏，鼠标放到末尾，显示，或者渲染在行号前面。

**Comment by purocean** [comment]
可以自定义模版  
<img width="447" alt="image" src="https://user-images.githubusercontent.com/7115690/236366663-3a46ff0d-e94b-4431-a566-ed756128b2c5.png">

**Comment by aiyou9** [comment]
> 可以自定义模版 <img alt="image" width="447" src="https://user-images.githubusercontent.com/7115690/236366663-3a46ff0d-e94b-4431-a566-ed756128b2c5.png">

但是，如果，在word中都是多级列表层级一样，但是使用的是不同的word样式名，就不能在yn的md 页面区分了
