### ISSUE TITLE
【功能增强】每一页，自动读取任务，在右侧渲染界面的顶部，渲染一个任务进度条

### ISSUE THREAD

**Issue by aiyou9** [purocean/yn#259]
就像这里的print进度条
![image](https://user-images.githubusercontent.com/15712822/233831659-41cbba3e-29f8-4704-ae45-fe0abde3cc18.png)

**Comment by purocean** [comment]
首先这个进度条就是待办的进度，其次新版本已经改成一个圆环了
![image](https://user-images.githubusercontent.com/7115690/234519386-6c47ca92-0ba4-4eb7-a0b9-5a33d2ab90f1.png)
