### ISSUE TITLE
[BUG]:ubuntu18.04 Yank-Note-linux-amd64-3.52.1.deb 安装成功 运行失败

### ISSUE THREAD

**Issue by xiangzebo** [purocean/yn#262]
3.52.1版本没有18.04的版本deb 之前的版本有并可以安装并运行成功。
3.52.1版本安装成功 但是运行失败
innerError Error: Cannot find module '../build/Debug/pty.node'

**Comment by purocean** [comment]
ubuntu 18.4 版本的构建系统已经失效。我在考虑直接集成二进制的方式来解决

**Comment by purocean** [comment]
考虑维护成本，ubuntu 18.4 后续不会支持了，你可以自己编译
