### ISSUE TITLE
[BUG]:切换标签页的时候，预览位置会乱跳，概率性出现

### ISSUE THREAD

**Issue by 71-MengYi** [purocean/yn#264]
**Describe the bug**
多个文档相互切换的时候，预览窗口的内容会四处跳，并且与编辑窗口的光标位置无关，有时候会直接跳到最顶部，有时候只是往上或者往下跳不远。没有其他任何操作，仅是标签页之间相互切换。

1. 仅标签页之间相互切换，小概率出现
2. 滑动编辑窗口后切换，稍微大些概率出现
3. 滑动预览窗口后切换，较大概率出现
4. 稍作编辑后切换，小概率出现

**Desktop (please complete the following information):**
 - Version v3.52.1
 - OS: macOS

**Comment by 71-MengYi** [comment]
文档中用了toc，宏替换，指定图片大小，有表格

**Comment by purocean** [comment]
针对文档较复杂的情况，保持上一次的滚动条位置有一些困难。目前我的使用情况感觉这个功能并不是很需要。更多的时候会带来困扰。因此这个[提交](https://github.com/purocean/yn/commit/2e3c233966891f8a544484acc1bb1f034d12c5ce)移除了这个特性。

另外，我还是希望在打开的文件之间切换时候能尽可能保持之前的文档的编辑状态，这个[提交](https://github.com/purocean/yn/commit/0fb430d57b29ce291c58f3374c254f74b21cdf2d)加上了这个功能
