### ISSUE TITLE
[BUG]:Crash about Run JS Code

### ISSUE THREAD

**Issue by longlongvip** [purocean/yn#272]
**Describe the bug**
Yank Note Crash, No Response

**To Reproduce**
1. Write the code
```js
// --run--
Array = [1, 2, 3, 4, 5]
console.log(Array);
```
2. Click on Run
3. Yank Note Crash, No Response

**Expected behavior**
Yank Note Crash, No Response

**Screenshots**
You try it

**Desktop (please complete the following information):**
 - Version v3.54.0
 - OS: Windows 11
 - Browser: Chrome

**Additional context**
Reopen Yank Note to solve the Problem
If run it in Console of Chrome, you can get **undefined**

**Comment by purocean** [comment]
https://github.com/purocean/yn/commit/0bfdeb3f9468112e16b4c759d582025eccb3f621
