### ISSUE TITLE
【需求】 支持自定义终端

### ISSUE THREAD

**Issue by keepstep** [purocean/yn#276]
类似vscode的可以选择终端程序
eg：用git-bash 替代 cmd

**Comment by purocean** [comment]
<img width="802" alt="image" src="https://github.com/purocean/yn/assets/7115690/4d7afd69-ae42-43eb-b749-8a49b48047e1">
看看设置中，有这一项配置

**Comment by keepstep** [comment]
👍👍👍

**Comment by keepstep** [comment]
使用自定义终端 C:\Git\bin\bash.exe **中文显示乱码**

在 yn 中 使用：
![image](https://github.com/purocean/yn/assets/58132194/f5834322-7f0a-4fa1-a589-c70bbbb79014)

在windows中使用：
![image](https://github.com/purocean/yn/assets/58132194/4c289e5d-b5eb-47d5-aacb-4e96dd1a4796)
