### ISSUE TITLE
[enhancement]: 编辑器可补全代码围栏语言

### ISSUE THREAD

**Issue by laivanyouxi** [purocean/yn#279]
请问能不能自己添加  ` 的代码块

比如
\```java
\```

\```c++
\```

cao，写错了，不是BUG
![Snipaste_2023-08-01_22-51-15](https://github.com/purocean/yn/assets/44131015/0f3a0dfb-31e6-4f5b-9a8f-27443587012c)

**Comment by purocean** [comment]
没太看明白？你是要加编辑器自动补全还是要加新的渲染语言？

**Comment by purocean** [comment]
https://github.com/purocean/yn/commit/de30946f187aa4f16c39d136ab5770cdaa2fa6de
