### ISSUE TITLE
单md的行数多的时候, 编辑器就特别卡, 键盘响应慢, 影响效率, 不知道有没有优化手段?

### ISSUE THREAD

**Issue by Ethanaslincy** [purocean/yn#281]
最近用yn写的文章内容有点大,  单页的内容多的时候, 编辑器就特别卡,  编辑模式的键盘响应好慢啊...影响效率, 不知道有没有优化手段?

_Originally posted by @Ethanaslincy in https://github.com/purocean/yn/issues/65#issuecomment-1670542363_

**Comment by purocean** [comment]
优化性能是 Yank Note 非常愿意做的事，是否可以 https://github.com/purocean/yn#supports 加我微信详细描述一下？

**Comment by purocean** [comment]
这个版本修复了一些内存泄露 https://github.com/purocean/yn/releases/tag/v3.60.1
