### ISSUE TITLE
[BUG]:导出空白

### ISSUE THREAD

**Issue by LucasZhanye** [purocean/yn#282]
**Describe the bug**

**To Reproduce**

不定时出现右上角的文件导出消失，工具栏的导出之后文件大小仅为2kb，内容空白
**Expected behavior**

**Screenshots**

![image](https://github.com/purocean/yn/assets/103245663/7186ab2b-233c-4443-918e-0dc5347ca61c)

![image](https://github.com/purocean/yn/assets/103245663/69e63b8f-7454-4e55-a8ee-92e496e8b72f)

![image](https://github.com/purocean/yn/assets/103245663/7af18321-10d8-4988-8876-e194346639cf)

**Desktop (please complete the following information):**
 - Version： 3.39.0
 - OS: windows
 - Browser chrome

**Additional context**

**Comment by purocean** [comment]
你打来的文件是 markdown 吗？用的是默认预览器吗？

**Comment by purocean** [comment]
3.39.0 是去年的版本。工具栏的这两个按钮展示状态在去年更改过。请升级新版本再试试。总的逻辑是Yank Note只在打开markdown文件和使用默认预览器的情况下，才支持导出

**Comment by LucasZhanye** [comment]
感谢答复，我使用的是Markdown文件，是默认浏览器。

升级最新版本后可解决。
