### ISSUE TITLE
[BUG]:中英混合时，不能对齐

### ISSUE THREAD

**Issue by yixingwang0517** [purocean/yn#283]
如图片所示，当中英文混合时，不能对齐

![2023-08-26_14-57](https://github.com/purocean/yn/assets/19835921/21b18210-b817-412a-9ffa-91afad510139)

**Comment by yixingwang0517** [comment]
环境：

NAME="Linux Mint"
VERSION="21.2 (Victoria)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.2"
VERSION_ID="21.2"

**Comment by purocean** [comment]
Monaco 编辑器和字体渲染问题，目前无法解决（可尝试设置编辑器字体），先关闭
