### ISSUE TITLE
[BUG]: Vim plugin doesn't work anymore

### ISSUE THREAD

**Issue by raguay** [purocean/yn#284]
**Describe the bug**
Pressing escape doesn't change into vim modes for navigating.

**To Reproduce**
1. Press Escape
2. try to press j,k,h,l to navigate.

**Expected behavior**
The cursor should move according to the vim keystroke.

**Desktop (please complete the following information):**
 - Version [3.59.2](https://github.com/purocean/yn/releases)
 - OS: macOS Ventura
 - Browser: Arc

**Comment by purocean** [comment]
I have not reproduce this  bug. please upgrade yank-note-extension-vim-mode extension to 1.1.0

**Comment by raguay** [comment]
Okay. I'm using 1.1.0 of the vim plugin. So I deleted it and reran the
whole program. Then the program said it has an update and I updated it
to 3.60.1 and reinstalled the plugin. Now it is working fine. Not sure what
the exact issue was, but at least I have it again. Thanks.
