### ISSUE TITLE
预览模式切换到编辑模式时，编辑的位置不在当前浏览的章节

### ISSUE THREAD

**Issue by vivio325** [purocean/yn#286]
预览模式切换到编辑模式时，编辑的位置会跳到上一次编辑的光标停留的位置
例1：刚开始打开文件，看到3.2节，alt+x切换为编辑模式，显示的光标位置是文件开头
例2：在编辑模式，将光标移动到4.1章节，再切换到预览模式，再点左侧章节，选择3.1， 想要编辑3.1, alt+x切换后，编辑光标仍然在4.1.

**Comment by purocean** [comment]
https://github.com/purocean/yn/commit/56c726c9ca7ca4f0a3e9bc0e70b68e3f9fd93b78 下个版本修复
