### ISSUE TITLE
Need a setting to disable the suggest widget from showing as the user types

### ISSUE THREAD

**Issue by mitin001** [purocean/yn#288]
Is there a way to disable the suggest widget from showing up as I type? If I need it, I can trigger it via the keyboard shortcut ^ space.

**Comment by purocean** [comment]
Please check [v3.61.1](https://github.com/purocean/yn/releases/tag/v3.61.1)

**Comment by mitin001** [comment]
@purocean I'm still getting the suggest widget showing up as I type even though I disabled it in settings:

<img width="686" alt="image" src="https://github.com/purocean/yn/assets/6477175/875890c4-afef-4899-bc5f-3a529154b540">

<img width="733" alt="image" src="https://github.com/purocean/yn/assets/6477175/475e03a9-016c-4a37-b997-6128ec76bee7">

**Comment by purocean** [comment]
Thank you for your feedback. Please check https://github.com/purocean/yn/releases/tag/v3.61.2

![image](https://github.com/purocean/yn/assets/7115690/c78dd50e-df2b-4fc9-b535-c94a25afbeb5)
