### ISSUE TITLE
[BUG]:仓库在局域网服务器的文件内附件打不开

### ISSUE THREAD

**Issue by ebasegykj** [purocean/yn#293]
**Describe the bug**

1.有2台电脑一台win一台mac原来各自仓库都是本地的,后为了方便就把仓库放在了同局域网内的服务器上.
2.局域网仓库内的文件2台电脑都可以访问,文件内添加的图片也都能正确显示.
3.打开文件内附件的时候win系统提示这个错误打不开,错误信息内容为如下.(文件是肯定存在的,位置也是对的)
"Windows找不到文件\ds923 home\yank note\FILES项目总结
so_rs422.md\so_rs422.pdf'。请确定文件名是否正确后，再试一次。" 
4.用mac点击附件就可以正常打开.
5.出现错误信息电脑为win11

![image](https://github.com/purocean/yn/assets/73980319/885597a3-4472-4a2e-a1b3-fbac3fba5eb7)
![2](https://github.com/purocean/yn/assets/73980319/fc913456-9cb2-4fe8-9288-17eced90206a)
![3](https://github.com/purocean/yn/assets/73980319/01cb9e1f-53ee-4e9e-9c24-570e691d3c7f)

 - Version [ v3.61.3]
 - OS: [ WIn11]

**出现问题的系统为win11下**

**Comment by purocean** [comment]
下个版本发 https://github.com/purocean/yn/commit/9133609d52a4562cfad140027c46235c7fa18dd8
