### ISSUE TITLE
[BUG]: PlantUML 报错：Dot Executable: /usr/local/bin/dot Dot executable cannot be read。Cannot find Graphviz.

### ISSUE THREAD

**Issue by yaoyuanmysql** [purocean/yn#298]
报错信息：
Dot Executable: /usr/local/bin/dot Dot executable cannot be read。Cannot find Graphviz.
![image](https://github.com/purocean/yn/assets/25978114/7c6ce097-c25e-4069-ba64-e9bcb0e8ccbf)

但是本地验证Graphviz是好的， 而且报错的是状态图。时序图正常，流程图正常：报错代码如下：
@startuml
scale 600 width
[*] -> State1
State1 --> State2 : Success
@enduml

![image](https://github.com/purocean/yn/assets/25978114/60bfe3f7-11dc-4937-b929-952298abc4af)

是yn里面的plantUML版本不对吗？没有看到可以设置的地方

**Comment by yaoyuanmysql** [comment]
我在Idea里面的plantUML插件是可以正常显示的， 说明本地环境没有问题

**Comment by yaoyuanmysql** [comment]
Idea里面的PlantUML插件：
![image](https://github.com/purocean/yn/assets/25978114/758558ca-f5e5-457a-b2c6-cfb01055e275)

yn里面的
![image](https://github.com/purocean/yn/assets/25978114/baf0fccc-7d1d-4b6c-8cff-fbe8bf9fbaf3)

**Comment by purocean** [comment]
会不会是 dot 版本不太对

**Comment by yaoyuanmysql** [comment]
我看了一下官方最新的版本是9.0, 没有给mac brew提供低版本的安装方式我就没有尝试了. 
目录都是好的,  我怀疑是yn用的plantUml和graphviz版本不兼容.
