### ISSUE TITLE
[BUG]:特定情况下加粗出现错误

### ISSUE THREAD

**Issue by conradsheeran** [purocean/yn#305]
**Describe the bug**
当有序列表的下一行出现加粗且加粗内容有“：”时会出现未加粗的情况

**To Reproduce**
1. 首先先输入一个有序列表
2. 然后在最后一个列表后输入:
> \*\*注意：\*\*（为了使得GIthub上能够显示markdown源代码所以使用了反斜杠，复现时不需要使用）
3. 会发现这个“注意：”未被加粗，将其导出为pdf也未加粗

**Screenshots**
<img width="964" alt="屏幕截图 2023-11-29 122502" src="https://github.com/purocean/yn/assets/72184315/970fa213-72d0-4fcc-b912-98bd7dc220b7">

**Desktop (please complete the following information):**
 - Version：3.64.2
 - OS: Windows 11

**Comment by purocean** [comment]
这应该是 markdown 规范，你可以参考这篇文章 https://juejin.cn/post/7064565848421171213
