### ISSUE TITLE
Code Runner 运行结果代码过长能否 结果展示内部滚动显示。

### ISSUE THREAD

**Issue by dekit-cn** [purocean/yn#306]
Code Runner 运行结果代码过长能否 结果展示内部滚动显示。
在 Code Runner 运行curl 代替 postman 能很好的进行分组 大纲管理。
但是 curl 的内容过多用 jq 优化显示后 就把整个页面撑大了，能否像 jupyter 一样 
结果内容限高，内部滚动查看。

**Comment by purocean** [comment]
改了一下，https://github.com/purocean/yn/commit/2466402612f2e1c01bab67bb89777fc21dbda83a

可以下载测试版体验
