### ISSUE TITLE
【功能请求】支持github开源文档项目的阅读，比如导入文档项目中的目录，并提供记录阅读进度等功能的支持

### ISSUE THREAD

**Issue by aiyou9** [purocean/yn#313]
目前以md文件，制作开源文档的项目有，Rmarkdown，julia doc， rust doc，还有基于JavaScript的一系列，希望yn能够增加读取开源文档原项目，读取目录，提供阅读进度，批注，等功能

**Comment by purocean** [comment]
这个功能目前不会支持
