### ISSUE TITLE
需求分析，使mindmap和md完全相通

### ISSUE THREAD

**Issue by xh542428798** [purocean/yn#314]
大佬您好，看到您的思维导图插件，我平常偶尔也一下obsidian，主要就是它有个插件我觉得非常棒，
叫[obsidian-enhancing-mindmap](https://github.com/MarkMindCkm/obsidian-enhancing-mindmap)

这个插件既可以让我在md文件里编辑，又可以在思维导图模式下编辑：

它以md格式创建思维导图，可以直接在思维导图界面制作，如下：
![image](https://user-images.githubusercontent.com/49368033/217719057-b0607ecf-0b8a-4a0c-b031-2a6a37738090.png)

更重要的，它可以当作md文件打开，如下：
![image](https://user-images.githubusercontent.com/49368033/217719166-26d88807-d17e-40fb-9a0a-38dd9d830bce.png)
md模式下发现，它根据md的标题层级直接渲染的导图模式。
![image](https://user-images.githubusercontent.com/49368033/217719338-ffa523aa-a3a3-4b8a-aead-027866626750.png)
这样，我可以很方便的利用md格式写注释，感觉非常方便，不知道这个可不可以学过来？
万分感谢！

**Comment by purocean** [comment]
有个 markmap 的扩展，你可以看一下是否满足你的需求
