### ISSUE TITLE
mac app无法引用drawio文件，提示文件不存在

### ISSUE THREAD

**Issue by qq85715512** [purocean/yn#318]
![image](https://github.com/purocean/yn/assets/6128123/58413bd1-eb35-4051-b5e2-fe173121fc01)
咨询下是使用的方式不对还是app版本不支持呢？

**Comment by purocean** [comment]
这是一个 BUG，请升级最新版 drawio 扩展

**Comment by qq85715512** [comment]
<img width="1029" alt="image" src="https://github.com/purocean/yn/assets/6128123/52784af9-51a5-4036-b3ea-5ea3fd360774">
已经升级值2.1.2最新版本了，但还是有问题呢？

**Comment by purocean** [comment]
升级 2.1.3 版本试试
