### ISSUE TITLE
[Feature request]: 能否加入自定义界面功能

### ISSUE THREAD

**Issue by sftykbm** [purocean/yn#322]
目前侧栏,编辑器及预览只能自左向右依次排列.
希望能够实现自定义此三项位置的功能,让用户能自由排列(比如自上向下排列,或侧栏在左边,右上为编辑器,右下为预览,等等), 谢谢!

**Comment by purocean** [comment]
有一个扩展“view-reverse”可以实现的一部分需求，其他更多没有计划
