### ISSUE TITLE
[BUG]:页面预览栏bug

### ISSUE THREAD

**Issue by yushuishu** [purocean/yn#325]
**Describe the bug**
在页面预览栏的空白地方，会看到很多横粗线，看着像乱码字符被水平线切割之后留下一半字符的样子。

1、所有文件打开都是这样的，并不是只针对固定的几篇文件。

2、之前版本是没有的，升级当前最新版本【[3.67.1】之后发现的。

3、已经尝试了多次重启了电脑，无效。

4、导出HTML文件和PDF文件不受影响，空白处正常。

**Screenshots**

![image](https://github.com/purocean/yn/assets/50919172/b13b1210-4939-41d2-81a2-8c989c41c419)

![image](https://github.com/purocean/yn/assets/50919172/fcea5632-7cde-4b4b-9b82-3aef981c77b0)

**Desktop (please complete the following information):**
 - Version [v3.67.1]
 - OS: [windows10]

**Comment by purocean** [comment]
看起来像渲染问题，你先试试浏览器中使用Yank Note看看有没有问题（托盘菜单，浏览器打开），然后更新下电脑显卡驱动看看？
