### ISSUE TITLE
[BUG]:Error: connect ECONNREFUSED 127.0.0.1:3044

### ISSUE THREAD

**Issue by sufferpriest** [purocean/yn#326]
> yank.note@3.67.1 dev
> vite --host 0.0.0.0

  VITE v4.5.2  ready in 616 ms

  ➜  Local:   http://localhost:8066/
  ➜  Network: http://10.10.1.9:8066/
  ➜  Network: http://172.17.0.1:8066/
  ➜  press h to show help
Failed to load url /api/settings/js (resolved id: /api/settings/js). Does the file exist?
12:48:45 PM [vite] http proxy error at /api/settings/js:
Error: connect ECONNREFUSED 127.0.0.1:3044
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
12:48:47 PM [vite] Failed to load source map for /others/semver.js.

sudo netstat -nl | grep 3044
empty
sudo netstat -nl | grep 8066
tcp        0      0 0.0.0.0:8066            0.0.0.0:*               LISTEN

**Comment by purocean** [comment]
You need to launch the Yank Note application first.

**Comment by sufferpriest** [comment]
> You need to launch the Yank Note application first.

I followed this page: https://github.com/purocean/yn/blob/develop/help/DEVELOP_ZH-CN.md
And after install all, I run "npm run dev", then open browser for http://10.10.1.9:8066/, then see the error.
So, what's mean of "You need to launch the Yank Note application first."? Can you tell me details?

**Comment by purocean** [comment]
> > You need to launch the Yank Note application first.
> 
> I followed this page: https://github.com/purocean/yn/blob/develop/help/DEVELOP_ZH-CN.md And after install all, I run "npm run dev", then open browser for http://10.10.1.9:8066/, then see the error. So, what's mean of "You need to launch the Yank Note application first."? Can you tell me details?

run `yarn start` or launch the applation you downloaded. Which will listen the 3044 port.
