### ISSUE TITLE
[BUG]: luckysheet 插件编辑功能无效

### ISSUE THREAD

**Issue by fzh890523** [purocean/yn#330]
**Describe the bug**

**To Reproduce**

1. 在 yn 中创建 luckysheet 并 link 到 md，可以正常渲染出空表格
2. 点击表格上的编辑
3. 弹出的编辑窗口较糊且无法做任何操作（见下图）

**Expected behavior**

能正常编辑

**Screenshots**

<img width="537" alt="image" src="https://github.com/purocean/yn/assets/3354862/de96a175-b4a3-480a-9973-42594ab5947f">

**Desktop (please complete the following information):**
 - Version [e.g. v3.23.0] v3.67.1
 - OS: [e.g. macOS] macos x64 和 win11 x64 都有该问题
 - Browser [e.g. chrome, safari] chrome

**Additional context**

**Comment by purocean** [comment]
https://github.com/purocean/yn/commit/48f18f3ba553d268ed57d86feaf2892b676d0df9
