### ISSUE TITLE
[Feature Request] luckysheet 能否支持 xlsx 或者其他方式支持 xls(x)

### ISSUE THREAD

**Issue by YonkaFang** [purocean/yn#331]
# 背景

考虑到互操作性，希望能支持更通用的 表格格式 xls 或 xlsx。  在 https://github.com/dream-num/Luckyexcel 主页看到它应该是支持 xlsx 的。

但在使用 yn 的 luckysheet 插件时，link xlsx 文件（`[Luckysheet-xlsx](test.xlsx){link-type="luckysheet"}`）会报错如下：
<img width="314" alt="image" src="https://github.com/purocean/yn/assets/14256206/7c3dacca-cf75-4d60-b8b3-667fbf9fcc7e">

# 期望

1. 能否让 luckysheet 支持 xlsx 文件？

2. 如果 1 不能达成，还有其他方式支持 xls/xlsx 吗？ 哪怕只支持一个功能子集

thanks.

**Comment by purocean** [comment]
Luckysheet 问题比较多，且官方也不再维护了，因此后续不会在现有的基础上增加更多功能。后续会考虑使用其他表格方案
