### ISSUE TITLE
Feature Request: Delete Local Image from Preview Pane via Right-Click

### ISSUE THREAD

**Issue by Flow-sandyu** [purocean/yn#341]
功能请求：预览区右键点击图片删除本地仓库中的图片

描述:
在使用 Yanknote 过程中，有时会因为多次粘贴同一张图片而导致本地仓库中存储了多余的图片。如果用户想要删除这些多余的图片，目前需要手动打开存储路径，找到并删除图片文件。这个过程较为繁琐，因此希望能够在 Yanknote 中直接提供删除图片的功能。

需求:
希望在 Yanknote 的预览区，用户右键点击图片时，可以选择从本地仓库中删除该图片

最后来一句感谢洋子，yn 雀氏好用

**Comment by Flow-sandyu** [comment]
再补充一个功能: 
就是希望在预览区右键点击图片时能出现复制图片的按钮，这样就不用点开图片再去复制了。

不知道这个需求别人有没有，我的使用场景是这样的: 
我先在私人仓库写文章草稿，然后编辑好后，会把文章cv到博客的仓库里，这个过程就要处理图片路径的问题。 如果图片多的话，也有一个临时解决办法，就是把图片全部上传到图床，这样就不用处理图片路径问题了

这是预览区右键点击图片的状态:
![image](https://github.com/purocean/yn/assets/72751523/28d4be5c-d984-423b-a676-30e8ec7a8df2)

这是点开图片后右键点击图片的状态:
![image](https://github.com/purocean/yn/assets/72751523/496ed4ee-65ef-483c-8492-47c9a0316c21)

**Comment by purocean** [comment]
#342

**Comment by Flow-sandyu** [comment]
https://github.com/purocean/yn/releases/tag/v3-next-11
 复制和删除图片功能，测试没问题
