### ISSUE TITLE
Keyboard binding not working for MacOS Swiss, German

### ISSUE THREAD

**Issue by CarsKo** [purocean/yn#346]
**Describe the bug**
Characters like curly brackets (basically all characters reachable with key combination Option + digit - key)  cannot be entered

**To Reproduce**
1. Installing and starting Yank-Note - without changing any configuration
2. Trying to type characters like []{{} (which is done via typing "Option key + 5 key" etc.)
3. Does not work no matter what setting is active for Language (Language = System, Language = English, ...)
-->

**Expected behavior**
Typing "Option key + 5 key" should enter the special character [

**Screenshots**

**Desktop (please complete the following information):**
 - Version 3.72.2
 - OS: macOS Sonoma 14.5
 - System language Swiss or German

**Additional context**

**Comment by purocean** [comment]
#255

**Comment by purocean** [comment]
In [v3.73.1](https://github.com/purocean/yn/releases/tag/v3.73.1)
You can disable or change the shortcuts of switching repositroy to avoid this problem.

Considering the keyboard layout is a very complicated thing for shortcuts, and I will focus on this issue when I have the energy to do so later. If you're interested, take a look at this blog post: https://blog-purocean.vercel.app/yank-note-10/
