### ISSUE TITLE
[BUG]:HTML语法的标题，跳转有问题

### ISSUE THREAD

**Issue by Y-JESSE** [purocean/yn#347]
如果标题是html语法，左侧的目录可以正确显示，但是点击目录不能正确跳转

**Comment by purocean** [comment]
贴一个例子吧

**Comment by Y-JESSE** [comment]
https://github.com/user-attachments/assets/9c2cf7aa-60c7-4b6a-abe1-ba29a2ffe010

点击html语法的标题，会回到页头的标题。这种情况下预览窗口也是工作不正常的

**Comment by purocean** [comment]
手动加一个 id 试试，这种 html 不做进一步支持了
