### ISSUE TITLE
[BUG]:更新到最新版本后，加密的密文不能解密，用老版本可以的

### ISSUE THREAD

**Issue by zhanxh** [purocean/yn#351]
更新到最新版本后，加密的密文不能解密，用老版本可以的。不管是windows的版本还是linux-x86版本都有这个问题。
![Uploading 截图 2024-09-15 10-29-39.png…]()

**Comment by zhanxh** [comment]
3.75.4已经出现了不能解密的请，具体是哪个版本开始的不清楚

**Comment by zhanxh** [comment]
3.75.4已经出现了不能解密的情况，具体是哪个版本开始的不清楚

**Comment by purocean** [comment]
图片看不到，我刚刚测试解密没问题。加微信描述一下吧，项目首页下方有二维码

**Comment by zhanxh** [comment]
> 图片看不到，我刚刚测试解密没问题。加微信描述一下吧，项目首页下方有二维码

就是提示”密码错误“，我另外一台机子上是3.75.3版本可以的，之后的版本都不行

**Comment by sbfwfnh** [comment]
zhanxh 大神能麻烦你更新一下 DeaDBeeF 的歌词插件吗？
我在 ubuntu24.04 和deepin23 的系统上加载歌词插件都出现以下问题，我自己用你修改的源码编辑，都 是一样的问题！
播放歌词曲，加载歌词是播放器就闪退，播放器版本是 1.9.6
错误日志内容是：

> We had a crash. Will not resume the saved session to avoid a crash cycle.
starting deadbeef devel [static]
server_start
searching for GUI plugins in /home/daoran/.local/lib64/deadbeef
searching for GUI plugins in /home/daoran/.local/lib/deadbeef
load_plugin_dir /home/daoran/.local/lib/deadbeef: scandir found 3 files
searching for GUI plugins in /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 60 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /opt/deadbeef/lib/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/daoran/.local/lib64/deadbeef
loading plugins from /home/daoran/.local/lib/deadbeef
load_plugin_dir /home/daoran/.local/lib/deadbeef: scandir found 3 files
loading plugins from /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 60 files
loading plugin /opt/deadbeef/lib/deadbeef/aac.so
loading plugin /opt/deadbeef/lib/deadbeef/adplug.so
loading plugin /opt/deadbeef/lib/deadbeef/alac.so
loading plugin /opt/deadbeef/lib/deadbeef/alsa.so
loading plugin /opt/deadbeef/lib/deadbeef/artwork.so
loading plugin /opt/deadbeef/lib/deadbeef/cdda.so
loading plugin /opt/deadbeef/lib/deadbeef/converter.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/dca.so
dlopen error: /opt/deadbeef/lib/deadbeef/dca.so: undefined symbol: dca_dynrng
trying /opt/deadbeef/lib/deadbeef/dca.fallback.so...
plugin dca.so not found or failed to load
loading plugin /opt/deadbeef/lib/deadbeef/ddb_dsp_libretro.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_dumb.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_misc_headerbar_GTK3.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_misc_quick_search_GTK3.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_mono2stereo.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_out_pw.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_shn.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_soundtouch.so
loading plugin /opt/deadbeef/lib/deadbeef/dsp_libsrc.so
loading plugin /opt/deadbeef/lib/deadbeef/ffap.so
loading plugin /opt/deadbeef/lib/deadbeef/ffmpeg.so
loading plugin /opt/deadbeef/lib/deadbeef/flac.so
loading plugin /opt/deadbeef/lib/deadbeef/gme.so
loading plugin /opt/deadbeef/lib/deadbeef/hotkeys.so
loading plugin /opt/deadbeef/lib/deadbeef/in_sc68.so
loading plugin /opt/deadbeef/lib/deadbeef/lastfm.so
loading plugin /opt/deadbeef/lib/deadbeef/m3u.so
loading plugin /opt/deadbeef/lib/deadbeef/medialib.so
loading plugin /opt/deadbeef/lib/deadbeef/mms.so
loading plugin /opt/deadbeef/lib/deadbeef/mp3.so
loading plugin /opt/deadbeef/lib/deadbeef/musepack.so
loading plugin /opt/deadbeef/lib/deadbeef/notify.so
loading plugin /opt/deadbeef/lib/deadbeef/nullout.so
loading plugin /opt/deadbeef/lib/deadbeef/opus.so
loading plugin /opt/deadbeef/lib/deadbeef/oss.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/psf.so
loading plugin /opt/deadbeef/lib/deadbeef/pulse.so
loading plugin /opt/deadbeef/lib/deadbeef/rg_scanner.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexec.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/sid.so
loading plugin /opt/deadbeef/lib/deadbeef/sndfile.so
loading plugin /opt/deadbeef/lib/deadbeef/supereq.so
loading plugin /opt/deadbeef/lib/deadbeef/tta.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_curl.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_zip.so
loading plugin /opt/deadbeef/lib/deadbeef/vorbis.so
loading plugin /opt/deadbeef/lib/deadbeef/vtx.so
loading plugin /opt/deadbeef/lib/deadbeef/wavpack.so
loading plugin /opt/deadbeef/lib/deadbeef/wildmidi.so
loading plugin /opt/deadbeef/lib/deadbeef/wma.so
starting plugin GTK3 user interface
starting plugin AAC player
starting plugin Adplug player
starting plugin ALAC player
starting plugin ALSA output plugin
starting plugin Album Artwork
starting plugin Audio CD player
starting plugin Converter
starting plugin Converter UI
starting plugin Converter UI
starting plugin Resampler (Libretro)
starting plugin DUMB module player
starting plugin Headerbar for GTK3 UI
starting plugin Quick search
starting plugin Mono to stereo
starting plugin PipeWire output plugin
starting plugin Shorten player
starting plugin Soundtouch
starting plugin Resampler (Secret Rabbit Code)
starting plugin Monkey's Audio (APE) decoder
starting plugin FLAC decoder
starting plugin Game-Music-Emu player
starting plugin Hotkey manager
starting plugin SC68 player (Atari ST SNDH YM2149)
starting plugin last.fm scrobbler
starting plugin M3U and PLS support
starting plugin Media Library
starting plugin mms vfs
starting plugin MP3 player
starting plugin MusePack decoder
starting plugin OSD Notify
starting plugin Null output plugin
starting plugin Opus player
starting plugin OSS output plugin
starting plugin Playlist Browser
starting plugin Playlist Browser
starting plugin PSF player using Audio Overload SDK
starting plugin PulseAudio output plugin
starting plugin ReplayGain Scanner
starting plugin Shell commands
starting plugin Shellexec UI
starting plugin Shellexec UI
starting plugin SID player
starting plugin WAV/PCM player
starting plugin SuperEQ
starting plugin tta decoder
starting plugin cURL vfs
starting plugin ZIP vfs
starting plugin Ogg Vorbis decoder
starting plugin VTX player
starting plugin WavPack decoder
starting plugin WildMidi player
starting plugin WMA player
starting plugin stdio vfs
starting plugin FFMPEG audio player
selected output plugin: ALSA output plugin
resume: track 133 pos 154.831284 playlist 6

**Comment by zhanxh** [comment]
早上在ubuntu24.04上无法无法加载歌词库，并没有发你你说的闪退问题，如果是新系统默认没有libgtkmm以及相关依赖。

**Comment by zhanxh** [comment]
> zhanxh 大神能麻烦你更新一下 DeaDBeeF 的歌词插件吗？ 我在 ubuntu24.04 和deepin23 的系统上加载歌词插件都出现以下问题，我自己用你修改的源码编辑，都 是一样的问题！ 播放歌词曲，加载歌词是播放器就闪退，播放器版本是 1.9.6 错误日志内容是：
> 
> > We had a crash. Will not resume the saved session to avoid a crash cycle.
> > starting deadbeef devel [static]
> > server_start
> > searching for GUI plugins in /home/daoran/.local/lib64/deadbeef
> > searching for GUI plugins in /home/daoran/.local/lib/deadbeef
> > load_plugin_dir /home/daoran/.local/lib/deadbeef: scandir found 3 files
> > searching for GUI plugins in /opt/deadbeef/lib/deadbeef
> > load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 60 files
> > found gui plugin ddb_gui_GTK2.so
> > added GTK2 gui plugin
> > found gui plugin ddb_gui_GTK3.so
> > added GTK3 gui plugin
> > load gui plugin
> > checking GUI plugin: GTK2
> > checking GUI plugin: GTK3
> > found selected GUI plugin: GTK3
> > loading plugin /opt/deadbeef/lib/deadbeef/ddb_gui_GTK3.so
> > loading plugins from /home/daoran/.local/lib64/deadbeef
> > loading plugins from /home/daoran/.local/lib/deadbeef
> > load_plugin_dir /home/daoran/.local/lib/deadbeef: scandir found 3 files
> > loading plugins from /opt/deadbeef/lib/deadbeef
> > load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 60 files
> > loading plugin /opt/deadbeef/lib/deadbeef/aac.so
> > loading plugin /opt/deadbeef/lib/deadbeef/adplug.so
> > loading plugin /opt/deadbeef/lib/deadbeef/alac.so
> > loading plugin /opt/deadbeef/lib/deadbeef/alsa.so
> > loading plugin /opt/deadbeef/lib/deadbeef/artwork.so
> > loading plugin /opt/deadbeef/lib/deadbeef/cdda.so
> > loading plugin /opt/deadbeef/lib/deadbeef/converter.so
> > loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk2.so
> > loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk3.so
> > loading plugin /opt/deadbeef/lib/deadbeef/dca.so
> > dlopen error: /opt/deadbeef/lib/deadbeef/dca.so: undefined symbol: dca_dynrng
> > trying /opt/deadbeef/lib/deadbeef/dca.fallback.so...
> > plugin dca.so not found or failed to load
> > loading plugin /opt/deadbeef/lib/deadbeef/ddb_dsp_libretro.so
> > loading plugin /opt/deadbeef/lib/deadbeef/ddb_dumb.so
> > loading plugin /opt/deadbeef/lib/deadbeef/ddb_misc_headerbar_GTK3.so
> > loading plugin /opt/deadbeef/lib/deadbeef/ddb_misc_quick_search_GTK3.so
> > loading plugin /opt/deadbeef/lib/deadbeef/ddb_mono2stereo.so
> > loading plugin /opt/deadbeef/lib/deadbeef/ddb_out_pw.so
> > loading plugin /opt/deadbeef/lib/deadbeef/ddb_shn.so
> > loading plugin /opt/deadbeef/lib/deadbeef/ddb_soundtouch.so
> > loading plugin /opt/deadbeef/lib/deadbeef/dsp_libsrc.so
> > loading plugin /opt/deadbeef/lib/deadbeef/ffap.so
> > loading plugin /opt/deadbeef/lib/deadbeef/ffmpeg.so
> > loading plugin /opt/deadbeef/lib/deadbeef/flac.so
> > loading plugin /opt/deadbeef/lib/deadbeef/gme.so
> > loading plugin /opt/deadbeef/lib/deadbeef/hotkeys.so
> > loading plugin /opt/deadbeef/lib/deadbeef/in_sc68.so
> > loading plugin /opt/deadbeef/lib/deadbeef/lastfm.so
> > loading plugin /opt/deadbeef/lib/deadbeef/m3u.so
> > loading plugin /opt/deadbeef/lib/deadbeef/medialib.so
> > loading plugin /opt/deadbeef/lib/deadbeef/mms.so
> > loading plugin /opt/deadbeef/lib/deadbeef/mp3.so
> > loading plugin /opt/deadbeef/lib/deadbeef/musepack.so
> > loading plugin /opt/deadbeef/lib/deadbeef/notify.so
> > loading plugin /opt/deadbeef/lib/deadbeef/nullout.so
> > loading plugin /opt/deadbeef/lib/deadbeef/opus.so
> > loading plugin /opt/deadbeef/lib/deadbeef/oss.so
> > loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk2.so
> > loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk3.so
> > loading plugin /opt/deadbeef/lib/deadbeef/psf.so
> > loading plugin /opt/deadbeef/lib/deadbeef/pulse.so
> > loading plugin /opt/deadbeef/lib/deadbeef/rg_scanner.so
> > loading plugin /opt/deadbeef/lib/deadbeef/shellexec.so
> > loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk2.so
> > loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk3.so
> > loading plugin /opt/deadbeef/lib/deadbeef/sid.so
> > loading plugin /opt/deadbeef/lib/deadbeef/sndfile.so
> > loading plugin /opt/deadbeef/lib/deadbeef/supereq.so
> > loading plugin /opt/deadbeef/lib/deadbeef/tta.so
> > loading plugin /opt/deadbeef/lib/deadbeef/vfs_curl.so
> > loading plugin /opt/deadbeef/lib/deadbeef/vfs_zip.so
> > loading plugin /opt/deadbeef/lib/deadbeef/vorbis.so
> > loading plugin /opt/deadbeef/lib/deadbeef/vtx.so
> > loading plugin /opt/deadbeef/lib/deadbeef/wavpack.so
> > loading plugin /opt/deadbeef/lib/deadbeef/wildmidi.so
> > loading plugin /opt/deadbeef/lib/deadbeef/wma.so
> > starting plugin GTK3 user interface
> > starting plugin AAC player
> > starting plugin Adplug player
> > starting plugin ALAC player
> > starting plugin ALSA output plugin
> > starting plugin Album Artwork
> > starting plugin Audio CD player
> > starting plugin Converter
> > starting plugin Converter UI
> > starting plugin Converter UI
> > starting plugin Resampler (Libretro)
> > starting plugin DUMB module player
> > starting plugin Headerbar for GTK3 UI
> > starting plugin Quick search
> > starting plugin Mono to stereo
> > starting plugin PipeWire output plugin
> > starting plugin Shorten player
> > starting plugin Soundtouch
> > starting plugin Resampler (Secret Rabbit Code)
> > starting plugin Monkey's Audio (APE) decoder
> > starting plugin FLAC decoder
> > starting plugin Game-Music-Emu player
> > starting plugin Hotkey manager
> > starting plugin SC68 player (Atari ST SNDH YM2149)
> > starting plugin last.fm scrobbler
> > starting plugin M3U and PLS support
> > starting plugin Media Library
> > starting plugin mms vfs
> > starting plugin MP3 player
> > starting plugin MusePack decoder
> > starting plugin OSD Notify
> > starting plugin Null output plugin
> > starting plugin Opus player
> > starting plugin OSS output plugin
> > starting plugin Playlist Browser
> > starting plugin Playlist Browser
> > starting plugin PSF player using Audio Overload SDK
> > starting plugin PulseAudio output plugin
> > starting plugin ReplayGain Scanner
> > starting plugin Shell commands
> > starting plugin Shellexec UI
> > starting plugin Shellexec UI
> > starting plugin SID player
> > starting plugin WAV/PCM player
> > starting plugin SuperEQ
> > starting plugin tta decoder
> > starting plugin cURL vfs
> > starting plugin ZIP vfs
> > starting plugin Ogg Vorbis decoder
> > starting plugin VTX player
> > starting plugin WavPack decoder
> > starting plugin WildMidi player
> > starting plugin WMA player
> > starting plugin stdio vfs
> > starting plugin FFMPEG audio player
> > selected output plugin: ALSA output plugin
> > resume: track 133 pos 154.831284 playlist 6

早上在ubuntu24.04上发现deadbeef确实无法无法加载歌词库，并没有发你你说的闪退问题。我的24.04是新安装的系统，它默认没有libgtkmm以及相关依赖。你试试我这个新的包，我拷贝了libgtkmm-3.0相关依赖so到lib目录，修改了启动方式。链接: https://pan.baidu.com/s/1ekqlFJKX5GZ0y9iYohyXSQ 提取码: e1xh

**Comment by sbfwfnh** [comment]
现在可以加载 歌词插件 启动没问题了，还是会闪退！
我在终端中运行，查看了一下返回结果。
一点播放，闪退后就返回如下：

SONG STARTED
Segmentation Fault
backtrace() returned 5 addresses
/home/daoran/Downloads/deadbeef/deadbeef() [0x420957]
/lib/x86_64-linux-gnu/libc.so.6(+0x3d1a0) [0x7f31cd4591a0]
/home/daoran/Downloads/deadbeef/plugins/ddb_lyricbar_gtk3.so(+0x3e8bf) [0x7f31ca4fa8bf]
/lib/x86_64-linux-gnu/libc.so.6(+0x893ac) [0x7f31cd4a53ac]
/lib/x86_64-linux-gnu/libc.so.6(+0x10a608) [0x7f31cd526608]

不管是复制到 opt 目录中运行，还是随便在哪里运行结果都一样，麻烦你抽时间看看，非常感谢！
