### ISSUE TITLE
如何使用列编辑？

### ISSUE THREAD

**Issue by NascaStar** [purocean/yn#354]
请问yank note是否支持列编辑呢？
支持的话要如何开启哇，比如快捷键之类的
不支持的话，请问后续有计划会添加么？

类似这种
![image](https://github.com/user-attachments/assets/7c139558-88a8-4b00-89ab-2276b70c058a)

**Comment by purocean** [comment]
和 VSCode 一样的操作逻辑。按住 Alt 单击，或者鼠标中键选文本，或者按快捷键
![image](https://github.com/user-attachments/assets/cf7e4c6f-4cca-44a1-ae32-dd7d1dde38f4)

![image](https://github.com/user-attachments/assets/19a836cf-acda-4bcb-83c1-32009c6f1b85)

**Comment by NascaStar** [comment]
👌 thx！
