### ISSUE TITLE
[BUG]: 中文的中括号不能自动转换成英文的中括号，导致wiki补全失败

### ISSUE THREAD

**Issue by CnsMaple** [purocean/yn#357]
**Describe the bug**

https://github.com/user-attachments/assets/c2cd79e3-2214-4497-9f35-64c1fd80ed68

**Desktop (please complete the following information):**
 - Version 3.76.2
 - OS: Windows
 - Browser None

**Additional context**

**Comment by purocean** [comment]
Windows 上有这个问题，下个版本修复

**Comment by purocean** [comment]
3.77.1 版本已修复
