### ISSUE TITLE
非代码块中，i*j会自动写成ij

### ISSUE THREAD

**Issue by vivio325** [purocean/yn#358]
在写题目时，非代码块中出现以下情况：

假设 i 和 j 是整型变量，以下语句_____的功能是在屏幕上显示形如 i*j=i*j的一句乘法口诀。例如，当 i=2，j=3时，显示2*3=6。
A. printf("d * %d=%d\n", i, j, i*j);

显示结果为
假设 i 和 j 是整型变量，以下语句_____的功能是在屏幕上显示形如 ij=ij的一句乘法口诀。例如，当 i=2，j=3时，显示2*3=6。
A. printf("d * %d=%d\n", i, j, ij);
B. printf("%d * %d=%d\n", i, j, i*j);

问题：
i*j中的*没有显示，且A和B的字体有区别，A选项斜体，B选项没有斜体

**Comment by vivio325** [comment]
我去，github也是这么显示的
原题目为
`假设 i 和 j 是整型变量，以下语句_____的功能是在屏幕上显示形如 i*j=i*j的一句乘法口诀。例如，当 i=2，j=3时，显示2*3=6。`
`A. printf("d * %d=%d\n", i, j, i*j);`
`B. printf("%d * %d=%d\n", i, j, i*j);`

**Comment by purocean** [comment]
这是 markdown 语法标准，你可以写 `\*` 在 符号前面加上斜杠来避免
