### ISSUE TITLE
[feat]: 大佬，有计划添加 Slidev的幻灯片支持吗？

### ISSUE THREAD

**Issue by ic-xu** [purocean/yn#359]
平时在使用过程中体验非常好，有时候在给同事分享的时候用到幻灯片，看看能否添加幻灯片支持

**Comment by jaywhj** [comment]
有了reveal，感觉就没必要了

**Comment by purocean** [comment]
slidev 比较复杂，暂时没有计划添加

**Comment by jaywhj** [comment]
> slidev 比较复杂，暂时没有计划添加

@purocean 对，有了reveal，slidev显得多余了，可以更新一下reveal吗？我看最新版的有很多特性。

**Comment by purocean** [comment]
已更新 reveal.js 扩展
