### ISSUE TITLE
软件终端中显示command not found，但是该命令在别的终端中是可以执行的

### ISSUE THREAD

**Issue by longczx** [purocean/yn#360]
![wechat_2024-11-10_162856_221](https://github.com/user-attachments/assets/b33a7f9c-f9fd-4769-a8ba-bc76ba5ea898)
![image](https://github.com/user-attachments/assets/c87f6807-bf24-4b18-90cf-2932e8e76864)

看起来 两者的shell和export都是一样的
还需要提供什么东西的话请告诉我

软件版本：[3.76.2](https://github.com/purocean/yn/releases)

OS：Deepin Linux

uname: Linux 6.6.47-amd64-desktop-hwe #23.01.00.37 SMP PREEMPT_DYNAMIC Tue Aug 20 17:33:52 CST 2024 x86_64 GNU/Linux

**Comment by purocean** [comment]
你试试在设置中配置一下环境变量，把一些目录加入 path 看看

**Comment by longczx** [comment]
> 你试试在设置中配置一下环境变量，把一些目录加入 path 看看

具体是哪些目录嘞，我之前尝试把git的可执行目录加到 环境变量中了，但是依旧是不work的
