### ISSUE TITLE
[BUG]:解析markdown的系列bug反馈和功能建议

### ISSUE THREAD

**Issue by jaywhj** [purocean/yn#361]
你好，我是YN的新用户，今天才第一次体验到，试用了一下，发现了一些问题，已经非常强大了，希望还能优化一下。

「Bug」：
1.本地资源不能加载，本地图片、音视频好像都加载不出来，比如：`![本地图片](/Users/aaron/Pictures/md-mty.jpg)`，图片是存在的，从github下载的也有沙盒限制吗？

2.img解析有问题，部分情况下，解析不出来，具体看图；
<img width="566" alt="iShot_2024-11-11_11 19 02" src="https://github.com/user-attachments/assets/4cee9345-a45c-4f6b-8270-c5ab91e61d40">

3.链接标题锚点解析有问题，正常情况下是支持解析的，只不过如果标题中包含空格，就识别不出来了。
	标题包含空格是非常普遍的，而且英文标题都是用空格来区分单词的。
	比如 `[显示文字](#1. 标题)`，解析不出来，因为1.的后面多了一个空格，`[显示文字](#1.标题)`这样能识别链接，但是点击链接不到标题锚点了

「Feature」：
1.体验改善：同步滚动的时候，流畅度还能改善吗？滚动编辑区，预览视图一顿一顿的，不是很流畅；
2.导出HTML或其他格式文件，如果能添加大纲目录就好了，这点Typora做的最好，可以参考；
3.数学公式，可以考虑添加内联公式的支持，就是行内只需要1个$的写法。现在支持块级公式，用2个$$；
4.补充化学方程式的解析支持，参考：[mhchem](https://mhchem.github.io/MathJax-mhchem/)；
5.导出HTML，如果选择使用markdown转换，会出现转换失败和报错，看错误信息是LaTeX数学公式不支持；
6.导出HTML的文件里，点击链接打开方式可以优化一下，如果是内部锚点链接，则在当前窗口直接滚动就行，不需要打开新窗口跳过去；如果是外部链接，则可以新开窗口；现在全部是新开窗口跳转；

「系统环境」
YN版本：3.76.2
系统：MacOS 12.2
浏览器：Chromium: 130.0.6723.116（正式版本）(arm64)

**Comment by jaywhj** [comment]
补充一个「Bug」
- 上面 「Feature」中的第3条 - 内联数学公式，原来不是不支持，是解析有bug：
    - 比如 `$ E=mc^2 $` 这个最简单的公式居然解析不出来 $E=mc^2$，今天才发现原来是 $ 号前后多了1个空格导致的。
       这个应该是正则表达式匹配的问题，而且很难不让用户添加首位的空格，用户也是无意的，所以需要匹配兼容性。

**Comment by jaywhj** [comment]
@purocean ，上午好
方便的话，可以优先修复markdown解析的基础bug🙏，拓展功能以后有空再说，比如：
1. <img>标签换行后的解析；
2. 内联数学公式的解析；
3. 链接标题锚点的问题；
4. plantuml依然不能渲染，最新3.76.2版本，已经设置了端点为online svg或png；
5. 导出html/PDF增加左侧目录大纲；

这些常用，其他的有空了你再看看，最后，开发辛苦啦！☺️
我还测试了类似产品VS Code，除了3，1-2-4都没问题，正确解析。Typora能正确解析3，希望能帮到你。

**Comment by purocean** [comment]
> 你好，我是YN的新用户，今天才第一次体验到，试用了一下，发现了一些问题，已经非常强大了，希望还能优化一下。
> 
> 「Bug」： 1.本地资源不能加载，本地图片、音视频好像都加载不出来，比如：`![本地图片](/Users/aaron/Pictures/md-mty.jpg)`，图片是存在的，从github下载的也有沙盒限制吗？
> 
> 2.img解析有问题，部分情况下，解析不出来，具体看图； <img alt="iShot_2024-11-11_11 19 02" width="566" src="https://private-user-images.githubusercontent.com/7008992/384776196-4cee9345-a45c-4f6b-8270-c5ab91e61d40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDg1NDgsIm5iZiI6MTczMjI0ODI0OCwicGF0aCI6Ii83MDA4OTkyLzM4NDc3NjE5Ni00Y2VlOTM0NS1hNDVjLTRmNmItODI3MC1jNWFiOTFlNjFkNDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjJUMDQwNDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2ViYTQ2Y2MxZmM4ZTQ4MjM4ZDlkMmI4YzRmMDNhOTQ1ZDk5Mzc3MDA3N2FjZjFjNjdmNTU5OWUwN2I5Nzg3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.BCbtKRJncgTfuvjB3ZOJdKAePQ7rd-kDONl-wdUWU70">
> 
> 3.链接标题锚点解析有问题，正常情况下是支持解析的，只不过如果标题中包含空格，就识别不出来了。 标题包含空格是非常普遍的，而且英文标题都是用空格来区分单词的。 比如 `[显示文字](#1. 标题)`，解析不出来，因为1.的后面多了一个空格，`[显示文字](#1.标题)`这样能识别链接，但是点击链接不到标题锚点了
> 
> 「Feature」： 1.体验改善：同步滚动的时候，流畅度还能改善吗？滚动编辑区，预览视图一顿一顿的，不是很流畅； 2.导出HTML或其他格式文件，如果能添加大纲目录就好了，这点Typora做的最好，可以参考； 3.数学公式，可以考虑添加内联公式的支持，就是行内只需要1个$的写法。现在支持块级公式，用2个$$； 4.补充化学方程式的解析支持，参考：[mhchem](https://mhchem.github.io/MathJax-mhchem/)； 5.导出HTML，如果选择使用markdown转换，会出现转换失败和报错，看错误信息是LaTeX数学公式不支持； 6.导出HTML的文件里，点击链接打开方式可以优化一下，如果是内部锚点链接，则在当前窗口直接滚动就行，不需要打开新窗口跳过去；如果是外部链接，则可以新开窗口；现在全部是新开窗口跳转；
> 
> 「系统环境」 YN版本：3.76.2 系统：MacOS 12.2 浏览器：Chromium: 130.0.6723.116（正式版本）(arm64)

**BUG**
1. 可以加上 `file://` 协议头，Yank Note 中的路径是相对仓库的，所以需要加上这个。但是需要注意，如果你在浏览器中使用，这个地址不会生效。如：`![本地图片](file:///Users/aaron/Pictures/md-mty.jpg)`
2. html 解析换行问题已记录
3. Markdown 解析标准就是没支持空格，Yank Note 里面你可以使用`-`代替空格。你可以使用 `ctrl + 单击预览区域标题` 形式来复制标题锚点

** Feature**
1. 预览区域滚动目前没精力优化，如果你有更好的建议可以联系我，可参考这个文章 https://juejin.cn/post/7055536166229000222
2. 导出功能优化已记录
3. 目前是支持行内公式的，你可以参考帮助文件。如果不生效，你要看看 `$` 符号周围是否有其他字符，或许跟 Markdown 解析标准有关 https://github.com/purocean/yn/issues/121
4. 已经记录，如果做的话会以扩展形式提供
5. Yank Note 使用 pandoc 来转换导出，可以研究一下这个，已记录
6. 导出的 HTML 锚点跳转优化，已记录

**Comment by jaywhj** [comment]
@purocean 好的，收到。

根据上面的回复，我还有几个问题需要探讨一下🙏：
1. 内联数学公式，我测试了，是支持的。但有时候为了美观，在`$` 前后无意加了空格就不渲染。这个其实好修复，正则匹配前后空格，主要是其他所有的markdown工具都能正确解析😂；
2. 链接标题锚点没问题👍，原来是要用`-`代替，之前不知道。可以补充一个描述在使用文档里，让其他用户都知道；
3. plantuml 依然不能渲染，最新3.76.2版本，已经设置了端点为 Online SVG 或 PNG；
4. 有没有计划更新一下插件 reveal.js，新版好多特效呀；

**Comment by purocean** [comment]
> @purocean 好的，收到。
> 
> 根据上面的回复，我还有几个问题需要探讨一下🙏：
> 
> 1. 内联数学公式，我测试了，是支持的。但有时候为了美观，在`$` 前后无意加了空格就不渲染。这个其实好修复，正则匹配前后空格，主要是其他所有的markdown工具都能正确解析😂；
> 2. 链接标题锚点没问题👍，原来是要用`-`代替，之前不知道。可以补充一个描述在使用文档里，让其他用户都知道；
> 3. plantuml 依然不能渲染，最新3.76.2版本，已经设置了端点为 Online SVG 或 PNG；
> 4. 有没有计划更新一下插件 reveal.js，新版好多特效呀；

1. 数学公式决定保持现状，目前的解析规则是专门考虑了不允许空格，因为 $ 不仅在公式中有意义，其他地方也有意义。我看了几个解析器都考虑了这种情况。
2. reveal.js 扩展已更新

**Comment by jaywhj** [comment]
好的，数学公式这个，没什么影响，我去掉空格就好了，优先解决其他的。
再补充一下化学公式的扩展，这样理工科数理化，搞学术研究的人都可以用起来了 👍。
