### ISSUE TITLE
[Feature Request] 打印PDF的时候是否可以增加---符号来来分割页

### ISSUE THREAD

**Issue by JerryXu2023** [purocean/yn#362]
打印PDF的时候是否可以增加---符号来来分割页的功能？

**Comment by purocean** [comment]
这里有一些样式类可以实现这个功能

https://github.com/purocean/yn/blob/develop/help/FEATURES_ZH-CN.md#%E5%85%83%E7%B4%A0%E5%B1%9E%E6%80%A7%E4%B9%A6%E5%86%99
