### ISSUE TITLE
无法删除文件，不支持在系统内部挂载上的丢弃到回收站操作，有解决方案么？

### ISSUE THREAD

**Issue by goldcome** [purocean/yn#365]
**Describe the bug**
无法删除文件，是哪里的权限需要设置

**Screenshots**
![image](https://github.com/user-attachments/assets/d58aa1e7-04c7-494c-9e89-450a0d0f48f6)

**Desktop (please complete the following information):**
 - Version 3.77.1
 - OS: ubuntu22.04

**Comment by goldcome** [comment]
日记中找到原因：` 不支持在系统内部挂载上的丢弃到回收站操作`

**Comment by purocean** [comment]
问了一下chatgpt

> 在 Ubuntu 22 上，如果尝试删除文件时收到提示“Trashing on system internal mounts is not supported”，这是因为文件系统的挂载方式或位置不支持使用“回收站”功能（Trash）。具体原因可能是：
> 
> 1. **文件系统类型不支持 Trash**：某些文件系统（例如 NTFS、FAT32、ext4 的特定配置）不支持将文件移入回收站。
> 2. **挂载方式**：挂载点（mount point）被标记为“系统内部”或特殊用途，Ubuntu 认为不应启用 Trash 功能。
> 3. **权限问题**：如果挂载点的权限不足，无法创建 Trash 目录。
> 
> 解决方法：
> 
> ### 方法 1：直接永久删除文件
> 如果确定这些文件可以直接删除，可以使用以下命令：
> 
> ```bash
> rm -rf /path/to/file_or_directory
> ```
> 
> **注意**：`rm -rf` 会永久删除文件，无法恢复，请谨慎操作。
> 
> ---
> 
> ### 方法 2：手动指定 Trash 目录
> 你可以手动设置一个 Trash 目录，然后移动文件到这个目录作为替代方案。例如：
> 
> 1. 创建一个全局 Trash 目录（假设为 `~/mytrash`）：
>    ```bash
>    mkdir -p ~/mytrash
>    ```
> 2. 将文件移动到此目录：
>    ```bash
>    mv /path/to/file_or_directory ~/mytrash/
>    ```
> 
> ---
> 
> ### 方法 3：检查挂载配置
> 如果你有权限调整挂载设置，可以尝试更改挂载方式，使其支持 Trash。
> 
> 1. **查看当前挂载点**：
>    ```bash
>    mount
>    ```
> 2. **调整挂载选项**：
>    编辑 `/etc/fstab` 文件，确保挂载点的选项支持写操作并标记为用户挂载。例如：
>    ```fstab
>    /dev/sdXn /mnt/mydisk ext4 defaults 0 2
>    ```
>    修改完成后，重新挂载：
>    ```bash
>    sudo mount -o remount /mnt/mydisk
>    ```
> 
> ---
> 
> ### 方法 4：使用 GUI 文件管理器
> 有时，文件管理器（如 Nautilus）可能提供了绕过 Trash 的选项：
> 1. 右键文件，选择“永久删除”。
> 2. 如果没有此选项，可以在删除时按住 `Shift` 键，跳过 Trash。
> 
> ---
> 
> 以上方法适用于不同场景，选择适合你的方式即可。

很久以前Yank Note 删除不依赖系统的回收站。我考虑一下后面是否做一个配置项加回来

**Comment by purocean** [comment]
https://github.com/purocean/yn/commit/c5e72d6aafc892610881d7f41876186ce084f594 已经调整为如果移动到回收站失败，询问是否需要直接删除。预计下个版本发布，你可以在[这里下载测试版本](https://github.com/purocean/yn/releases)试试
