### ISSUE TITLE
[BUG]:双击打开md文档只会打开yk笔记软件不会打开文档，还需要再次双击文档才行

### ISSUE THREAD

**Issue by sjhsbhqf** [purocean/yn#367]
**Describe the bug**
双击打开md文档只会打开yn笔记软件不会打开文档，还需要再次双击文档才行

**To Reproduce**
1. 双击md文档
2. yn软件会启动
3. 但是软件没有打开md文档
4. 再回到资源管理器双击md文档，这时yn软件才打开了md文档

**Expected behavior**
双击md文档后，yn软件自动打开md文档

**Desktop:**
 - Version 不知道在哪查看版本，找半天
 - OS: windows11 Version 23H2 (OS Build 22631.4460)

**Comment by purocean** [comment]
确实有这个问题，下个版本修复
