### ISSUE TITLE
Katex公式中如果出现中文无法解析，但是在typora中可以正常解析

### ISSUE THREAD

**Issue by 15805383399** [purocean/yn#45]
![image](https://user-images.githubusercontent.com/76238405/123383563-ef993180-d5c5-11eb-9ab0-139ef17407c4.png)
我想把之前typora下写的一些文档导入进来，然后发现含有中文的公式无法解析

**Comment by purocean** [comment]
@15805383399 项目 Katex 依赖版本太低了，不支持中文。我升级了一下，你可以先在这里试验一下 https://yn-phi.vercel.app

然后你可以下载 3.0 beta 版本 https://github.com/purocean/yn/releases/tag/v3.0.0-beta-03

感谢反馈 :)

**Comment by 15805383399** [comment]
切换到beta版本之后，大部分的公式都正常识别了，但是有的公式还是有无法识别的情况
并且经过测试，发现如果公式的开头结尾使用 $$ $$，而不是内联公式（使用$ $）的写法，是可以正常识别的
并且使用内联公式的写法在typora中是可以识别的
例如：
$W= \int_{V_1}^{V_2}P\ dV=C\int_{V_1}^{V_2}V^{-\gamma}dV= C \frac{V^{1-\gamma}_2-V^{1-\gamma}_1}{ 1- \gamma }$
![image](https://user-images.githubusercontent.com/76238405/123417855-e4a4c800-d5ea-11eb-9fe1-6f513027a99a.png)
![image](https://user-images.githubusercontent.com/76238405/123418472-aeb41380-d5eb-11eb-9401-fbc3de6b61cb.png)
$(C*_{v,m}+R)P\ dV = -C_*{v,m}V\ dP$
![image](https://user-images.githubusercontent.com/76238405/123418738-fa66bd00-d5eb-11eb-9f5d-e8b90efc9601.png)
![image](https://user-images.githubusercontent.com/76238405/123418365-904e1800-d5eb-11eb-97b4-5e4ac65730fe.png)

**Comment by purocean** [comment]
@15805383399 
我是用的 https://github.com/waylonflinn/markdown-it-katex 来做公式解析。你试试内联公式 $ 前面不要加空格，应该能解析

**Comment by 15805383399** [comment]
删掉空格之后确实可以解析了，感谢
