### ISSUE TITLE
使用相对路径添加图片在yank-note 必须使用 ./ 开头，直接写文件名无法识别

### ISSUE THREAD

**Issue by 15805383399** [purocean/yn#46]
使用相对路径添加图片在yank-note 必须使用 ./ 开头，直接写文件名无法识别
直接使用文件名添加图片在typora以及vscode中使用markdown all in one 都可以识别
![image](https://user-images.githubusercontent.com/76238405/123420153-c42a3d00-d5ed-11eb-90ff-85f8d111abee.png)
![image](https://user-images.githubusercontent.com/76238405/123420273-f176eb00-d5ed-11eb-8f9f-e7cad5739e2f.png)
![image](https://user-images.githubusercontent.com/76238405/123420318-018eca80-d5ee-11eb-91d9-44b6fb8a0491.png)

**Comment by purocean** [comment]
嗯这是一个已知问题。之前做路径解析太粗糙了，V3 会优化 https://github.com/purocean/yn/projects/5#card-63823027

**Comment by purocean** [comment]
现在能更准确解析相对路径了 https://github.com/purocean/yn/commit/5522c4c92cb800f5ec6c8c86da79c2881727e5e3
