### ISSUE TITLE
在ubuntu下无法正常显示图标

### ISSUE THREAD

**Issue by 15805383399** [purocean/yn#47]
![image](https://user-images.githubusercontent.com/76238405/123421320-42d3aa00-d5ef-11eb-8c94-1cad7d82b083.png)
可以检索到在 /usr/share/icons/hicolor/0x0/apps 这个路径下有正确的，且没有损坏的图标的 png文件
![image](https://user-images.githubusercontent.com/76238405/123421776-e329ce80-d5ef-11eb-8eaf-2d7060005e5f.png)
![image](https://user-images.githubusercontent.com/76238405/123422024-33089580-d5f0-11eb-84d9-385dc4cfe52d.png)
![image](https://user-images.githubusercontent.com/76238405/123422092-46b3fc00-d5f0-11eb-95d0-57ee5ca5d5b7.png)
并且我很奇怪为什么这个图标被放在了0x0 这个文件夹下，而不是512x512 这个文件夹下，而且也只有yank-note这一个程序使用了0x0这个文件夹

**Comment by purocean** [comment]
我没有 Linux 设备，打包出的效果也是随缘。如果你愿意可以帮助改进一下 😃

**Comment by 15805383399** [comment]
将图标文件拷贝到 /usr/share/pixmaps 目录下就可以正常显示图标了，但是我不知道怎么打包

**Comment by 15805383399** [comment]
> 将图标文件拷贝到 /usr/share/pixmaps 目录下就可以正常显示图标了，但是我不知道怎么打包

并且这个方法只能解决在总应用程序目录中不显示图标的问题
在dock中仍然不显示图标
![image](https://user-images.githubusercontent.com/76238405/123433380-fcd21280-d5fd-11eb-8385-e4d915215d86.png)
我在网上查找资料后，发现这因该只是ubuntu里面的问题
https://blog.csdn.net/chenqk_123/article/details/112962391
electron打包的程序在ubuntu下很多都有图标的问题。
按照这个博客里面的解释，deepin等系统里面dock的图标取决于.desktop 文件里面配置的图标，但是ubuntu下dock上显示的图标取决于创建窗口时引入的图标。
于是这个博客里面对于dock上不显示图标给出的解决方案就是直接在创建窗口时引入一张图片。
![image](https://user-images.githubusercontent.com/76238405/123434089-b16c3400-d5fe-11eb-91fd-839fcc109e1f.png)

**Comment by purocean** [comment]
看样子似乎和这个有关，我搞个虚拟机看看

https://github.com/electron-userland/electron-builder/issues/5294

**Comment by purocean** [comment]
@15805383399 现在已经修复图标不能展示的问题，你可以试试新的 Beta 版本

**Comment by 15805383399** [comment]
> @15805383399 现在已经修复图标不能展示的问题，你可以试试新的 Beta
dock上可以正常显示图标了

**Comment by purocean** [comment]
在这个提交修复 https://github.com/purocean/yn/commit/e833f96f01973db6e856fbe53b2547460189dbe2
