### ISSUE TITLE
在线体验版，在新建一个md文件之后会自动填充FEATURES.md的内容；以及渲染混乱的问题

### ISSUE THREAD

**Issue by 15805383399** [purocean/yn#48]
在线体验版，在新建一个md文件之后会自动填充FEATURES.md的内容
![image](https://user-images.githubusercontent.com/76238405/123507216-d44c2600-d69a-11eb-8d80-6d72fef414f7.png)
并且在全选之后，如果直接粘贴大段文本来覆盖掉 自动填充进去的内容，右侧的渲染结果会出现混乱
（经测试，全选删除后，再进行粘贴不会出现混乱）
![image](https://user-images.githubusercontent.com/76238405/123507278-1f663900-d69b-11eb-9778-fec8548ecb05.png)
并且在全选删除之后，右侧的渲染结果不会消失
![image](https://user-images.githubusercontent.com/76238405/123507324-54728b80-d69b-11eb-9d1d-4ee495406604.png)

然后我测试了ubuntu上的版本
在yank note 内新建md文件并没有自动填充FEATURES.md的内容
然后，我手动将FEATURES.md的内容粘贴进新建的md文件，渲染正常
![image](https://user-images.githubusercontent.com/76238405/123507462-23468b00-d69c-11eb-87ac-8ce79f74fcc2.png)
之后，与在 在线体验版中的操作相同，将同样的大段文本直接粘贴进去
右侧渲染结果混乱，仍然出现了FEATURES.md的内容
![image](https://user-images.githubusercontent.com/76238405/123507509-6f91cb00-d69c-11eb-9e9d-e18a49f76b22.png)
全部删除后，右侧渲染结果没有变化
![image](https://user-images.githubusercontent.com/76238405/123507549-a10a9680-d69c-11eb-8910-63c568c44f61.png)
撤销删除操作，关闭软件后台再重新启动，之前新建的文件渲染正常
![image](https://user-images.githubusercontent.com/76238405/123507595-ef1f9a00-d69c-11eb-9988-7460b30984d0.png)
同时，重启之后，打卡的第一个文件一定渲染正常，但是点开另一个文档之后，比如 readme.md，再切换回第一个文档就回出现渲染混乱的情况
![image](https://user-images.githubusercontent.com/76238405/123507730-a9170600-d69d-11eb-8cc4-c1e98b4fcb67.png)

**Comment by 15805383399** [comment]
这是我用来进行测试的文档
链接: https://pan.baidu.com/s/1N6JbRF8paf06Ms8Zi2PJtA  密码: ne3d

**Comment by purocean** [comment]
在线 DEMO 只是一个示例，所以无论什么文件读取都是读取的 FEATURES.md 文件。这里可以加一个提示避免困惑。然后下面的渲染问题，本质原因是和 markdown-it-attrs 插件有冲突 https://github.com/arve0/markdown-it-attrs/issues/115 ，也就是公式后面如果用 `{}` 结尾而没有其他任何字符，就会出错。我看看是不是想个办法避免一下。

**Comment by purocean** [comment]
这个提交修复 https://github.com/purocean/yn/commit/de8bfcd539e11571d9b675b87b90b0e449ae62e6#diff-8607b4d05e339e21c00a3f5ce7df53c49cfd6a7403dbf87210c06fc66bfd8450R101

**Comment by purocean** [comment]
#
