### ISSUE TITLE
在预览模式下，鼠标左键点击空白处，页面会跳动

### ISSUE THREAD

**Issue by G1aRe** [purocean/yn#52]
这个是跳到对应的编辑行吗？可不可以不跳动呢

**Comment by purocean** [comment]
修复了，预计下个版本发布。你也可以在 DEMO 页面测试下是不是符合预期 https://yn-phi.vercel.app/#/

**Comment by G1aRe** [comment]
嗯嗯，在预览模式下是不会乱跳了
