### ISSUE TITLE
转为PDF之后，文字无法选中

### ISSUE THREAD

**Issue by G1aRe** [purocean/yn#59]
转为PDF之后，像是图片格式的，文字无法选中。
代码区的背景也没有了，不知道这个算不算问题。

**Comment by purocean** [comment]
你是用什么方式导出PDF的？用系统自带打印功能导出没问题。浏览器打印功能需要勾选背景色才能展示代码背景色

**Comment by G1aRe** [comment]
![1](https://user-images.githubusercontent.com/17924947/131624488-5f739a40-f9a2-4020-9de3-2a73371d4709.png)
用这两个都不行

**Comment by purocean** [comment]
我测试也不行了，你试试用 Chrome 打开页面，再导出 PDF，应该可以。我评估一下看增强一下导出功能

**Comment by purocean** [comment]
你可以试试 [v3.6.0](https://github.com/purocean/yn/releases/tag/v3.6.0) 版本，增加了导出面板，这里导出的 PDF 可以选择文字了。另外要代码块支持背景色，需要勾选”包含背景“选项。

**Comment by G1aRe** [comment]
Perfect ！
