### ISSUE TITLE
UI调整建议

### ISSUE THREAD

**Issue by travin-cn** [purocean/yn#60]
1、右边的展示框、左边的文件区需要可手动隐藏或者显示，因为编辑区太小了
2、终端希望加个图标可以点击关闭
3、希望单独增加快捷键的帮助文档，README文件太长太复杂了
4、代码运行的UI希望可以再美化一下：”------------------------------------“这样有点丑

**Comment by purocean** [comment]
感谢反馈。第 1 点现在已有这个功能，状态栏“视图”菜单即可看到相关功能。其他建议收到。

**Comment by purocean** [comment]
2，3 点安排在v3计划中
