### ISSUE TITLE
源码构建、打包步骤

### ISSUE THREAD

**Issue by MichaelChen666** [purocean/yn#66]
建议，readme中增加源码构建、打包步骤，本地执行 ./scripts/install.sh 或 yarn、npm install，总是卡在这报各种错误：

yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @vue/compiler-sfc@3.1.1" has incorrect peer dependency "vue@3.1.1".
warning "@vue/eslint-config-standard > eslint-import-resolver-webpack@0.12.2" has unmet peer dependency "webpack@>=1.11.0".
warning " > @vue/eslint-config-typescript@5.1.0" has incorrect peer dependency "@typescript-eslint/eslint-plugin@^2.7.0".
warning " > @vue/eslint-config-typescript@5.1.0" has incorrect peer dependency "@typescript-eslint/parser@^2.7.0".
warning " > autoprefixer@10.2.6" has unmet peer dependency "postcss@^8.1.0".
[4/4] Building fresh packages...
[1/5] ⠁ node-pty
[-/5] ⠁ waiting...
[5/5] ⠁ electron
[4/5] ⠁ esbuild

**Comment by purocean** [comment]
构建步骤你可以参考 CI 流程 .github\workflows\release.yml 。具体你现在这个安装问题，需要你能科学上网，然后耐心点，祝你好运
