### ISSUE TITLE
只能打开仓库里的文件，而不能打开任意本地路径的文件吗？

### ISSUE THREAD

**Issue by kicoliu** [purocean/yn#85]
我用的windows版

**Comment by purocean** [comment]
https://juejin.cn/post/7035276236473499661#heading-2

这里我解释了原因，未来可能做临时打开文件功能，但应该不会做文件关联。如果要编辑 Markdown 文件还有更多的编辑器可以选择。

> Q: 为什么不做文件关联，可以直接打开 Markdown 文件的功能？  
A: 正如上面所说，Yank Note 异常开放，有代码运行，宏替换，HTML 解析等功能。为了更高的拓展性，几乎将内部能力完全放开，包括一些危险的能力如命令执行，任意文件读写等，因此我没做文件关联功能。只能从仓库打开，可以让用户更谨慎的打开外来文件。

**Comment by kicoliu** [comment]
OK，了解了。主要是用文件拖拽、打开方式强行打开等手段操作，界面会刷一下，但没有提示，以为有bug😃
