### ISSUE TITLE
关于全局搜索

### ISSUE THREAD

**Issue by lxb6476** [purocean/yn#86]
感谢作者的工作，想问下目前yn支持全局搜索功能吗？类似于vscode中在一个项目目录中搜索包含关键词的文件。

**Comment by lxb6476** [comment]
抱歉，打扰了，看到了issue中有人提过了~

**Comment by purocean** [comment]
看来这个功能太隐蔽不够醒目。未来有计划做一个“控制中心”

https://github.com/purocean/yn/projects/5#card-75177509

**Comment by purocean** [comment]
搜索功能现在是很粗暴的文本匹配，未来也有计划做倒排索引

https://github.com/purocean/yn/projects/5#card-70866879

**Comment by purocean** [comment]
#13
