### ISSUE TITLE
can not open yank note

### ISSUE THREAD

**Issue by utszcrystal** [purocean/yn#87]
in macbookpro,  use yank note for a period of time， buf suddenly appear the following error，and can not open yank md file
![image](https://user-images.githubusercontent.com/3824086/148317889-beb07819-979a-4f68-8719-9149deb26ad5.png)

**Comment by purocean** [comment]
macOS 版本多少？尽量不要用商店的版本，用 GitHub 的版本

https://github.com/purocean/yn/issues/83
