### ISSUE TITLE
是否可以在linux上只跑服务端，通过浏览器访问像code-server一样

### ISSUE THREAD

**Issue by stonytjd** [purocean/yn#89]
现在的linux版本在没有桌面环境的情况下无法运行，如果能在无桌面环境的linux系统上运行，通过浏览器访问就太好了。

**Comment by purocean** [comment]
以前是 Node 搞的，现在很多功能依赖 Electron 了，不太好改回去了

https://github.com/purocean/yn/issues/63
https://github.com/purocean/yn/issues/11
