### ISSUE TITLE
如果能作为vscode插件，依托git仓库作存储及同步，那就完美了。

### ISSUE THREAD

**Issue by mokeyish** [purocean/yn#9]

**Comment by purocean** [comment]
你可以试试这个 VSCode 插件，超级强悍。但是我更喜欢浏览器一点。

https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced

**Comment by mokeyish** [comment]
现在用的是有道云笔记跨端的，它好的地方就是目录，标签颜色标记，搜索这些比较好，但是有道云的笔记是存在它的服务器上的。vscode直接写markdown保存到本地文件夹还是不方便，我想存在自己的私密或者公开的git仓库不是更安全。

**Comment by purocean** [comment]
我之前也把东西保存到 git，每次推拉不方便，所以直接用 OneDrive 了。以前云笔记爆发时候用了不少，后来都算了。现在只用自己写这个，还有就是 OneNote。

**Comment by mokeyish** [comment]
所以需要插件把vscode变成笔记，自动同步。取笔记修改时间+部分内容作为git 日志。

**Comment by mokeyish** [comment]
你开发的这个看起来不错

**Comment by purocean** [comment]
嗯，你可以尝试搞一下 git 支持
