### ISSUE TITLE
所见即所得

### ISSUE THREAD

**Issue by linonetwo** [purocean/yn#95]
我最近在打算给我的 https://github.com/tiddly-gittly/TidGi-Desktop 做所见即所得，调研了一下 Monaco 没法做 WYSIWYG ，你这方面是怎么打算的呢？

**Comment by purocean** [comment]
不做 :)

> Q: 为什么要使用编辑预览分开，而不是所见即所得？ A: 一来是因为我喜欢文本，我喜欢控制文本，我更喜欢代码的方式来写东西。二是技术原因，富文本编辑器很难做好。我体验过不少富文本编辑器/组件，都很难达到我想要的体验，还不如直接文本来得直接。

https://juejin.cn/post/7035276236473499661
