### ISSUE TITLE
导出为pdf时的默认文件名多了个“.md”

### ISSUE THREAD

**Issue by KAWAKO-in-GAYHUB** [purocean/yn#96]
虽然可以手动删掉，不影响使用，但是有点别扭哈哈哈

![image](https://user-images.githubusercontent.com/54660064/153819078-188ae84c-eca5-4ecb-ba7a-50687b3fe9b4.png)

![image](https://user-images.githubusercontent.com/54660064/153819218-13f160b0-1bdb-47dd-b537-6a6011018259.png)

**Comment by purocean** [comment]
下个版本发

相关提交: https://github.com/purocean/yn/commit/6f6cdcaaf820437ab57279b9f1ebb840c77fe00b

**Comment by purocean** [comment]
v3.24.0 已调整 https://github.com/purocean/yn/releases/tag/v3.24.0
