### ISSUE TITLE
Plantuml预览加载不出来

### ISSUE THREAD

**Issue by kicoliu** [purocean/yn#99]
三五行的还可以，行数多了，右侧预览就出不来图形，一直在转圈。但是点击放大器，在新窗口是可以加载出图形的。

用安装包自带的plantuml.jar独立运行啥的也都很正常

**Comment by purocean** [comment]
@kicoliu 
软件版本是多少？是偶发还是必现？有示例图形代码吗？

我刚刚测试表现都比较正常

**Comment by kicoliu** [comment]
@purocean 
今天刚下载的最新版，在两台不同的机器环境也都试过了，存在相同问题。
测试代码如下（多次试验好像跟里面的名称长短有关，比如名称都起成 A/B/C/D这样的就能正常显示）：

`
@startuml
package {
    [unifiedLLM]
    [optoptLLM]
    [ethvcLLM]
    [osuLLM]
}

[portal] <--> [unifiedLLM]
[PCECP] <-> [unifiedLLM]

[unifiedLLM] <--> [optoptLLM]
[unifiedLLM] <--> [ethvcLLM]
[unifiedLLM] <--> [osuLLM]

[optoptLLM] <--> [inv]
[ethvcLLM] <--> [inv]
[osuLLM] <--> [inv]
@enduml
`

**Comment by purocean** [comment]
加微信聊一下吧，我还是没能复现 https://github.com/purocean/yn#supports

**Comment by purocean** [comment]
v3.24.0 已修复 https://github.com/purocean/yn/releases/tag/v3.24.0
